### PR TITLE
Ensure that addresses are not synced until addresses have been defined

### PR DESCRIPTION
**Pull request by lulf**
As proposed in #3101

### CODE REVIEW

**Comment by vbusch** [comment]
I like the waiting until the addresses are initializized.  A different different approach is to wait until the listeners are available.  See https://github.com/vbusch/enmasse/tree/init-watchers

**Comment by lulf** [comment]
I've been able to verify this patch manually following the steps in #3101 

@vbusch I'm not sure what approach I prefer. If you would like to use the other approach, I'm happy to close this. In any case, it would be good to get a fix in so that we can start release builds...

**Comment by grs** [comment]
@vbusch if the listeners are added in the same tick as the watcher is created, then I believe they can't miss the first event (which will have to be in the next tick at earliest). However you could also move the address_source.start() after the listeners are registered, which perhaps is more intuitively correct anyway.

**Comment by vbusch** [comment]
@grs yes, I agree, that it would probably be impossible for the event to be processed in that tick.  Created https://github.com/lulf/enmasse/pull/3 as a precaution.

**Pull request merged**
