### PR TITLE
Remove unused keycloak console integration

### PR DESCRIPTION
**Pull request by lulf**
* Remove all code related to setting up Keycloak identity provides, console oauth settings and admin users.
* Update CSV with permissions needed for console service
* Update CHANGELOG.md with console change
* Remove some entries from npm-shrinkwrap

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by lulf** [comment]
@enmasse-ci run tests profile=upgrade

**Comment by lulf** [comment]
@k-wall How about removing docs and systemtests but keep type in api for backwards compatibility?

**Comment by lulf** [comment]
@enmasse-ci run tests profile=smoke

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=UserApiTest

**Comment by kornys** [comment]
@lulf so test for federated user in user api test should be removed as well

**Comment by lulf** [comment]
@kornys it is done

**Pull request merged**
