### PR TITLE
ensure results count is updated when addresses change

### PR DESCRIPTION
**Pull request by grs**
fix for #949 (updated to check that filterconfig is initialised)

### CODE REVIEW

**Comment by tkratky** [comment]
@grs could we enable web console tests that verify this fix within this PR? (No. 26. https://github.com/EnMasseProject/enmasse/issues/824)

**Comment by grs** [comment]
@tkratky yes, can you confirm the tests? That issue has three, but two seem to be the same one (line 106 is not disabled). The second test is now marked as also failing due to another unopened issue so I have left that disabled but revised the comment.

**Comment by tkratky** [comment]
@grs : enabled tests for brokered as well, so now everything looks fine, thank you!

**Comment by grs** [comment]
@tkratky doh! sorry, got confused by the similar filename and tests!

**Pull request merged**
