### PR TITLE
Switch to Go 1.12.9

### PR DESCRIPTION
**Pull request by ctron**
Following up on #2951, this PR switches Travis to Go 1.12.9.

### CODE REVIEW

**Comment by kornys** [comment]
@ctron do we need to update go in jenkins openstack instances as well?

**Comment by ctron** [comment]
> @ctron do we need to update go in jenkins openstack instances as well?

Yes, and we will also need support for our Maven+Java+Go+AllTheRest image on PNC as well.

**Comment by ctron** [comment]
@enmasse-ci run tests profile=smoke

**Comment by kornys** [comment]
@ctron @lulf I have created new images in openstack with go 1.12.9, so before merging this PR please let me know and I will switch images in jenkins

**Pull request merged**
