### PR TITLE
Detect Infinispan protocol errors and fail the service

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by lulf** [comment]
@dejanb @ctron Should this be closed or is it waiting for some other PR?

**Comment by ctron** [comment]
> @dejanb @ctron Should this be closed or is it waiting for some other PR?

I forgot about this one. Will take another look.

**Comment by ctron** [comment]
I just re-tested this one. It seems that the client is actually re-connecting, it just takes a bit longer than expected.

**Pull request closed without merging**
