### PR TITLE
Minor documentation fixes

### PR DESCRIPTION
**Pull request by fgiorgetti**
### Type of change

- Documentation

### Description

Minor fixes to the documentation.

### Checklist

Not applicable

### CODE REVIEW

**Comment by k-wall** [comment]
@fgiorgetti thanks for the contribution, it is very welcome.

**Comment by hmaclean73** [comment]
@fgiorgetti If these doc fixes apply to release-0.33 and release-0.32, can you please add them to those branches as well?

**Comment by k-wall** [comment]
@hmaclean73 could you review please?

**Comment by lulf** [comment]
@fgiorgetti Would you mind rebasing this on master?

**Comment by fgiorgetti** [comment]
@lulf doing it now.

**Pull request closed without merging**
