### PR TITLE
Fix - console does not show custom address plan properly

### PR DESCRIPTION
**Pull request by drcoolsanjeev**
### Type of change
- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Description
- fix issue - console does not show custom address plan properly.
- show metadata.name as label for plan if spec.displayName is not present in response of addressPlan

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
Surely this same issue applies to address space plans too? They too have a displayName which is also could be empty.

**Comment by kornys** [comment]
@drcoolsanjeev test passed, plan is shown properly

**Comment by drcoolsanjeev** [comment]
@lulf , for short description (optional) , what should we replace with? should I replace shortDescripiton with shortDescription || longDescription || "<empty string>"?

**Comment by lulf** [comment]
@drcoolsanjeev I'm a bit divided if it should be `shortDescription || longDescription || ""` or just `shortDescription || ""`. We don't really have any guidance on what longDescription should be, but I think your suggestion is probably fine for now.

**Comment by lulf** [comment]
@drcoolsanjeev Will you make the change to use displayName for address space plans in a separate PR?

**Comment by anukritijha** [comment]
@lulf Sanjeev has created a separate issue for the same and raised a PR.

**Pull request merged**
