### PR TITLE
Try to run CI using kind

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by obabec** [comment]
I would be happy to migrate to kind but I think if we move we should still run (for example once a week) master job also on minikube to be sure, that we have covered this platform too. WDYT? @lulf

**Comment by lulf** [comment]
@obabec Yeah, another master workflow that doesn't push images to quay.io then?

**Comment by obabec** [comment]
@lulf Exactly, I'll handle after kind if working, sounds reasonable for you?

**Comment by obabec** [comment]
@lulf I think you are missing registry. That needs to be deployed too.

**Pull request merged**
