### PR TITLE
Systemtests iot workarounds

### PR DESCRIPTION
**Pull request by famartinrh**
### Type of change

- Bugfix

### Description

This PR adds a few workaorunds around the iot cleanup process to ensure errors are captured and logged and to ensure every cleanup step is executed
Includes #3652

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [X] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by famartinrh** [comment]
@enmasse-ci run tests profile=iot

**Comment by famartinrh** [comment]
@enmasse-ci run tests profile=iot testcase=io.enmasse.systemtest.iot.shared.**

**Comment by famartinrh** [comment]
@enmasse-ci run tests profile=iot

**Comment by famartinrh** [comment]
@enmasse-ci run tests testcase=**.MqttAdapterTest,**.ManagedTest

**Comment by famartinrh** [comment]
@enmasse-ci run tests testcase=**.MqttAdapterTest,**.ManagedTest

**Comment by famartinrh** [comment]
@enmasse-ci run tests profile=iot

**Comment by kornys** [comment]
I think we have around 30 iot tests, so why it triggered only 13?

**Comment by famartinrh** [comment]
no longer needed

**Pull request closed without merging**
