### PR TITLE
Control endpoint exposure via address space controller config

### LINKED ISSUE #1398: Using empty addressSpace endpoint list along with services doesn't work anymore
As a way of configuring external loadbalancer annotations and properties in endpoints (see #661), we create an addressSpace with an empty endpoint list (`"endpoints": [],`)  and deploy our own endpoint services (with `type: LoadBalancer` label), so that these are adopted as endpoints via `EndpointController.updateEndpoints()`.

With EnMasse 0.21.0 however, this doesn't work anymore. There is this exception, occuring repeatedly:
````
2018-06-21 13:32:13.335 [Thread-4] INFO  ControllerChain:109 - Check address spaces: [hono:default]
2018-06-21 13:32:13.354 [Thread-4] INFO  CreateController:72 - Creating address space {name=default,namespace=hono,type=standard,plan=unlimited-standard-without-mqtt,endpoints=[],status={isReady=false,endpointStatuses=[],messages=[]}}
2018-06-21 13:32:14.088 [Thread-4] WARN  ResourceChecker:53 - Exception in checker task
java.lang.IllegalArgumentException: No value available for parameter name: CONSOLE_SECRET
  at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:203)
  at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:157)
  at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.processLocally(TemplateOperationsImpl.java:59)
  at io.enmasse.controller.common.KubernetesHelper.processTemplate(KubernetesHelper.java:123)
  at io.enmasse.controller.TemplateInfraResourceFactory.createResourceList(TemplateInfraResourceFactory.java:85)
  at io.enmasse.controller.CreateController.handle(CreateController.java:104)
  at io.enmasse.controller.ControllerChain.onUpdate(ControllerChain.java:120)
  at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:48)
  at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:40)
  at java.lang.Thread.run(Thread.java:748)
````

Related commit:
https://github.com/EnMasseProject/enmasse/commit/12d3ebbf07d0d83541136d99d8b5db08dc8631ea#diff-c1906ad2f12f179d2ea72800cf87281cL85

(The `Step 3: Create missing secrets if not specified` in `TemplateInfraResourceFactory.createResourceList` has been removed, so template params aren't set anymore.)

### PR DESCRIPTION
**Pull request by lulf**
* Always create endpoints for services by default
* Add configuration option to address space controller config to remove exposure
* Add service host to cert CN

Next step is to allow individual endpoints to be expose.

Fixes #1398

### CODE REVIEW

**Comment by calohmn** [comment]
@lulf In the case that `addressSpace.getEndpoints()` is an empty, I guess there is still the exception from #1398. Although the workaround for #661 wouldn't involve an empty endpoints list anymore, I think it would be good to handle that case - could also be by just logging an error about that being an invalid address space config.

**Comment by lulf** [comment]
@calohmn Some tests were failing, hoping the next test run will fix that.

**Comment by calohmn** [comment]
@lulf did a test with `bash deploy.sh -n hono -t kubernetes -o singletenant -a standard`.
There is an issue now with the keycloak-controller not creating the realm. The following block gets repeated in keycloak-controller:
````
2018-06-27 10:10:58 INFO  KeycloakManager:81 - Actual: [master], Desired: [hono]
2018-06-27 10:10:58 INFO  KeycloakManager:91 - Creating realm hono
2018-06-27 10:10:58 INFO  KeycloakManager:37 - getConsoleEndpoint: checking {name=messaging,host=null,service=messaging,servicePort=amqps,cert={provider=selfsigned,secretNameexternal-certs-messaging}}
2018-06-27 10:10:58 INFO  KeycloakManager:37 - getConsoleEndpoint: checking {name=amqp-wss,host=null,service=messaging,servicePort=https,cert={provider=selfsigned,secretNameexternal-certs-messaging}}
2018-06-27 10:10:58 INFO  KeycloakManager:37 - getConsoleEndpoint: checking {name=mqtt,host=null,service=mqtt,servicePort=secure-mqtt,cert={provider=selfsigned,secretNameexternal-certs-mqtt}}
2018-06-27 10:10:58 INFO  KeycloakManager:37 - getConsoleEndpoint: checking {name=console,host=null,service=console,servicePort=https,cert={provider=selfsigned,secretNameexternal-certs-console}}
2018-06-27 10:10:58 INFO  KeycloakManager:39 - getConsoleEndpoint: found console endpoint {name=console,host=null,service=console,servicePort=https,cert={provider=selfsigned,secretNameexternal-certs-console}}
2018-06-27 10:10:58 INFO  KeycloakManager:53 - getConsoleEndpointStatus: checking {name=messaging,host=null,serviceHost=messaging.hono.svc,port=31729}
2018-06-27 10:10:58 INFO  KeycloakManager:53 - getConsoleEndpointStatus: checking {name=amqp-wss,host=null,serviceHost=messaging.hono.svc,port=32145}
2018-06-27 10:10:58 INFO  KeycloakManager:53 - getConsoleEndpointStatus: checking {name=mqtt,host=null,serviceHost=mqtt.hono.svc,port=30891}
2018-06-27 10:10:58 INFO  KeycloakManager:53 - getConsoleEndpointStatus: checking {name=console,host=null,serviceHost=console.hono.svc,port=32121}
2018-06-27 10:10:58 INFO  KeycloakManager:55 - getConsoleEndpoint: found console endpoint status {name=console,host=null,serviceHost=console.hono.svc,port=32121}
2018-06-27 10:10:58 INFO  KeycloakManager:102 - Address space default console endpoint host not known, waiting
````

**Comment by lulf** [comment]
@calohmn I think travis fails on the same thing, will have a look

**Pull request merged**
