### PR TITLE
Allow creation of addresses with an empty status obj

### PR DESCRIPTION
**Pull request by vbusch**
Fixed null pointer, and allowed the creation of addresses with empty status objects.

Signed-off-by: Vanessa <vbusch@redhat.com>

### Type of change

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by lulf** [comment]
We already support creating addresses with empty status field, I'm not sure why this change is necessary (I.e. you can kubectl create -f address.yaml with status missing).

**Comment by k-wall** [comment]
I don't understand the issue being solved.   I tried an oc apply with the following document (with an empty status map) and the queue was created successfully and went to Active.

```
apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
  name: standard.myqueue1
  addressSpace: standard
spec:
  address: myqueue1
  type: queue
  plan: standard-small-queue
status: {}
```

**Comment by lulf** [comment]
Could you test this fix @vbusch https://github.com/EnMasseProject/enmasse/pull/3689  I think it brings go and java code in sync.

**Comment by ctron** [comment]
I ran into the same issue, and came up with a similar change: https://github.com/EnMasseProject/enmasse/pull/3679/commits/f6b6096472dd5c42611ebfff78ea5656fc44eb45

Not having the check breaks the creation of addresses:

~~~
2020-01-17T10:38:01.141Z WARN  [ResourceChecker] Exception in checker task
java.lang.NullPointerException: null
	at io.enmasse.controller.standard.AddressProvisioner.checkQuotaForAddress(AddressProvisioner.java:269)
	at io.enmasse.controller.standard.AddressProvisioner.addQuotaForAddress(AddressProvisioner.java:148)
	at io.enmasse.controller.standard.AddressProvisioner.checkQuota(AddressProvisioner.java:137)
	at io.enmasse.controller.standard.AddressController.onUpdate(AddressController.java:320)
	at io.enmasse.k8s.api.ResourceChecker.doWork(ResourceChecker.java:51)
	at io.enmasse.k8s.api.ResourceChecker.run(ResourceChecker.java:41)
	at java.base/java.lang.Thread.run(Thread.java:834)
~~~

**Comment by lulf** [comment]
I still argue that adding the null-checks is not fixing the root cause. The fields should not be nullable, and if they are set to null, its a bug in the client code. Hopefully #3693 will let us know if client is attempting to set them.

**Comment by vbusch** [comment]
Closing.  Will create a new patch, if I see issues again.

**Pull request closed without merging**
