### PR TITLE
Fix a layout issue with the incoming/outgoing link tables

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by grs** [comment]
@ctron can you describe what the layout problem was exactly?

**Comment by grs** [comment]
@ctron tahnks! And was this in general, for all addresses? or for a specific address-type and/or circumstance?

**Comment by ctron** [comment]
> @ctron tahnks! And was this in general, for all addresses? or for a specific address-type and/or circumstance?

IIRC this was only for addresses backed by a broker

**Comment by grs** [comment]
thanks @ctron ! (and sorry for delay!)

**Comment by ctron** [comment]
Thanks for merging!

**Pull request merged**
