### PR TITLE
Try fixing flaky test, detecting proper postgresql startup

### PR DESCRIPTION
**Pull request by ctron**
### Type of change

- Bugfix

### Description

Try to work around the issue of detecting Postgres to be ready.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by kornys** [comment]
@ctron is it still actual?

**Comment by ctron** [comment]
> @ctron is it still actual?

No, it seemed the change didn't fix the issue completely.

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot

**Pull request merged**
