### PR TITLE
simply re-create certificates

### LINKED ISSUE #4953: k8s-tls/create script is not triggered if root-cert.pem exists
**Describe the bug**
k8s-tls sctipt is not triggered in IoTTestSession because condition check only build/root-cert.pem. So tests failed becasue root-cert.pem seems exist in templates folder but other certs are missing.

**Expected behavior**
create scripts should be triggered if ony required cert is missing

### PR DESCRIPTION
**Pull request by ctron**
### Type of change

- Refactoring

### Description

closes #4953

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@ctron Im confused :) you removed also call of create script so certificates are not created

**Comment by ctron** [comment]
> @ctron Im confused :) you removed also call of create script so certificates are not created

:facepalm: It clearly isn't you who is confused … time for weekend!

**Comment by ctron** [comment]
Should be fixed now. Thanks!

**Comment by kornys** [comment]
🙂🙂 agreed time for weekend🙂

**Pull request merged**
