### PR TITLE
Fix isolated tests

### PR DESCRIPTION
**Pull request by obabec**

### CODE REVIEW

**Comment by obabec** [comment]
@enmasse-ci run tests profile=isolated test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=isolated test_only

**Comment by kornys** [comment]
@enmasse-ci run tests profile=isolated test_only

**Comment by kornys** [comment]
@enmasse-ci run tests profile=isolated test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=isolated test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=isolated test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=isolated test_only

**Comment by kornys** [comment]
@enmasse-ci run tests test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=isolated test_only

**Pull request merged**
