### PR TITLE
Remove mqtt tests

### PR DESCRIPTION
**Pull request by kornys**
### Type of change

- Refactoring

### Description

remove old mqtt tests

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests test_only

**Comment by rgodfrey** [comment]
+1

**Comment by kornys** [comment]
@enmasse-ci run tests test_only

**Comment by kornys** [comment]
@enmasse-ci run tests test_only

**Comment by kornys** [comment]
@lulf do you think we can merge it?

**Comment by lulf** [comment]
Yes, I think so. I will have a look through the tests for usage of topic-large or topic-xlarge plans which are the only ones that work with mqtt

**Pull request merged**
