### PR TITLE
Terminate old addresses through garbage collection

### PR DESCRIPTION
**Pull request by lulf**
* Reuse status checks when terminating
* Ensure pooled addresses can handle status check success on termination

Issue #701

### CODE REVIEW

**Comment by lulf** [comment]
@grs Would it be much work to have the console set address phase to Terminating instead of deleting the configmap when address is deleted?

**Comment by grs** [comment]
No, I don't think so. Which component deletes them?

**Comment by lulf** [comment]
@grs Currently the standard controller, since it has the status checks to verify that router has been de-configured, broker deleted etc. It could be moved to agent if we move the status checks there.

**Comment by lulf** [comment]
@grs If deleting the configmap and removing the address from the broker is done at the same time, theres not much point. If they are not, the configmap could be kept until the address is deleted from the broker.

**Pull request closed without merging**
