### PR TITLE
Modified OLM install

### PR DESCRIPTION
**Pull request by jankalinic**
### Description
Now the install depends on upstream/downstream run.

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests profile=olm ocp4

**Comment by kornys** [comment]
@enmasse-ci run tests profile=olm ocp4

**Review by kornys — DISMISSED** [review]
LGTM but wait for CI results

**Comment by kornys** [comment]
@enmasse-ci run tests profile=olm ocp4

**Comment by zschwarz** [comment]
@enmasse-ci run tests profile=olm ocp4

**Comment by zschwarz** [comment]
@enmasse-ci run tests profile=olm ocp4

**Review by kornys — APPROVED** [review]

**Pull request merged**
