### PR TITLE
Split the travis build and run a second build, validating S2I

### PR DESCRIPTION
**Pull request by ctron**
Split up the travis build into two jobs, running in parallel.

The first job is the existing configuration, and the second job runs the S2I builder to ensure "buildability" on the sources.

The job split is done in order to reduce the chance to run into the 50 minute job limit of travis.

### CODE REVIEW

**Comment by ctron** [comment]
This should successfully compile now that #2356 was merged

**Comment by ctron** [comment]
This is currently blocked by sundrio/sundrio#129 …

**Comment by ctron** [comment]
Raised PR: sundrio/sundrio#131

**Comment by ctron** [comment]
Well, it is not testing this, but checking "buildability", current the issue is, that the build with S2I later on fails, due to the sundrio issue. Adding this to the travis build ensure that no code gets merged which later on breaks the build.

And it doesn't impact the main build, as this is a second build job and thus doesn't count towards the 50 minute build timeout.

**Comment by lulf** [comment]
Wdyt @kornys

**Comment by kornys** [comment]
LGTM

**Pull request merged**
