### PR TITLE
Refactor console ui code 

### LINKED ISSUE #4270: In console, if there is only one option use it as default
**Overview**

What is the feature/change being proposed, what use case does it solve?

Select the only available option in the console as default

**Design**

If you have a more detailed design in mind, or as you plan to implement this feature, write a design doc with the details. Use the [template](https://github.com/EnMasseProject/enmasse/blob/master/documentation/design/proposals/design-template.adoc) and raise a PR with the design doc, and link to this issue.

**Tasklist**

If/when you can, enumerate the tasks required to complete the feature in order to track progress as the feature is implemented.

### PR DESCRIPTION
**Pull request by drcoolsanjeev**
### Type of change
- Bugfix
- Refactoring
- Documentation

### Description
- update patternfly version to latest
- refactor folder structure and code of console-ui 
- improve coding standards for the front-end work
- create reusable components as much as possible
- refactor queries to replacing repetitive task for creating filter string to a function
- FIx #4270 auto select dropdown item if there is single option for dropdown

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests profile=shared testcase=web.**

**Comment by anukritijha** [comment]
> Looks good to me. Given the amount of changes and my unfamiliarity with the code, I'm not able to provide much more feedback. Does the console ui design doc need an update after this refactoring?

@lulf The design doc is already up to date with the changes for this PR.

**Comment by vbusch** [comment]
@enmasse-ci  run tests testcase=*ConsoleTest

**Comment by drcoolsanjeev** [comment]
@vbusch , Yes, We have no idea on system tests, @kornys can you please take a look into the system tests?

**Comment by vbusch** [comment]
A quick look at [io.enmasse.systemtest.isolated.web.FirefoxConsoleTest.testEditAddressSpace](https://maas-jenkins-csb-amq-online.cloud.paas.psi.redhat.com/job/enmasse-master-folder/job/enmasse-pr/483/testReport/junit/io.enmasse.systemtest.isolated.web/FirefoxConsoleTest/testEditAddressSpace/) shows it is failing with "Unable to locate element: //a[contains(text(), 'Edit')]" 
The [screenshot](https://maas-jenkins-csb-amq-online.cloud.paas.psi.redhat.com/job/enmasse-master-folder/job/enmasse-pr/483/artifact/artifacts/openshift-logs/logs/selenium_tests/io.enmasse.systemtest.isolated.web.FirefoxConsoleTest/testEditAddressSpace/io.enmasse.systemtest.isolated.web.FirefoxConsoleTest.testEditAddressSpace_2020-04-22_14%3A50%3A04%3A961.png), shows that it has correctly opened the action menu, and the edit button is visible. Most likely the xpath needs updating. (//a[contains(text(), 'Edit')])

If you want to try running them, https://github.com/EnMasseProject/enmasse/blob/master/HACKING.md has the instructions.  And the results for this PR are found at: https://maas-jenkins-csb-amq-online.cloud.paas.psi.redhat.com/job/enmasse-master-folder/job/enmasse-pr/483/

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests profile=shared testcase=web.**

**Comment by ajaypratap003** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Comment by ajaypratap003** [comment]
> ###  Test Summary 
> **TEST_PROFILE**: pr
> **TEST_CASE:** *ConsoleTest
> **TOTAL:** 88
> **PASS:** 78
> **FAIL:** 3
> **SKIP:** 7
> **BUILD_NUMBER:** 628
> **BUILD_ENV:** oc cluster up
> 
> ###  Test Failures 
> * testPurgeAddress in io.enmasse.systemtest.shared.brokered.web.FirefoxConsoleTest
> * testFilterAddressesByStatus in io.enmasse.systemtest.shared.standard.web.FirefoxConsoleTest
> * testPurgeAddress in io.enmasse.systemtest.shared.standard.web.FirefoxConsoleTest

@kornys and  @k-wall , We have fixed all the systemtests which were failing due to UI changes/refactoring but still some tests are failing which are not related to UI changes. Some times tests are failed due to other issues not UI. We have already spend more time on systemtests. Could you please have a look on below failed tests so that we can plan to merge this branch.
Please let us know if any change required from UI side.

1. I checked testPurgeAddress test which is not failing due to UI changes.
2. testFilterAddressesByStatus test is failing due to address status Failed. We don't have Failed status anymore, not sure but somehow Failed status is append with element item id which is causing issue. I checked snapshot for this test, it shows that status dropdown don't have Failed. Still test is picking Failed status somehow.

    io.enmasse.systemtest.shared.brokered.web.FirefoxConsoleTest.testPurgeAddress
    io.enmasse.systemtest.shared.standard.web.FirefoxConsoleTest.testFilterAddressesByStatus
    io.enmasse.systemtest.shared.standard.web.FirefoxConsoleTest.testPurgeAddress

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=shared.standard.web.FirefoxConsoleTest#testFilterAddressesByStatus crc

**Comment by k-wall** [comment]
@drcoolsanjeev I think the test failure relates to a UI defect, rather than a test or backend issue.

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests profile=shared testcase=web.**

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests profile=shared testcase=web.**

**Comment by kornys** [comment]
@enmasse-ci run tests profile=shared testcase=FirefoxConsoleTest#testFilterAddressesByStatus crc

**Comment by kornys** [comment]
@enmasse-ci run tests profile=shared testcase=FirefoxConsoleTest#testFilterAddressesByStatus crc

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Pull request merged**
