### PR TITLE
[Systemtests] Console server test

### PR DESCRIPTION
**Pull request by kornys**
### Type of change

- Enhancement / new feature

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=web.**

**Comment by famartinrh** [comment]
@enmasse-ci run tests testcase=web.**

**Comment by lulf** [comment]
Deletable?

**Comment by famartinrh** [comment]
I think so, just in case let's wait for David

**Pull request closed without merging**
