### PR TITLE
Systemtests infra configs

### PR DESCRIPTION
**Pull request by kornys**

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by lulf** [comment]
@kornys Seems like a lot of work to maintain Java POJOs for systemtests, would it be possible to reuse classes from api-model, or do you want it to be an 'independent' implementation?

**Comment by kornys** [comment]
@lulf yeah it is a lot of work, that would be a good idea, but is it posible, with current state of classes in api-model, convert obejct to json like in systemtests classes? Or we need to modify classes in api-model?

**Comment by lulf** [comment]
You just need an ObjectMapper instance  and the objects support json encoding.

Use mapper.writeValueAsString. Look for it’s use in api-model

**Comment by kornys** [comment]
@lulf so do you think we can reuse AddressSapceBuilder etc... in systemtests?

**Comment by lulf** [comment]
@kornys yes they are part of api model(generated)

**Comment by kornys** [comment]
@lulf ok I will create task for that and will do that in different PR

**Pull request merged**
