### PR TITLE
Handle upgrade from a version without router in json

### PR DESCRIPTION
**Pull request by lulf**
Issue #3190

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=upgrade

**Comment by lulf** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=upgrade upgrade_from=0.28.2

**Comment by kornys** [comment]
@enmasse-ci run tests profile=upgrade upgrade_from=0.28.2

**Comment by kornys** [comment]
@enmasse-ci run tests profile=upgrade upgrade_from=0.28.2

**Pull request merged**
