### PR TITLE
systemtests log pods on test error

### PR DESCRIPTION
**Pull request by famartinrh**

### CODE REVIEW

**Comment by famartinrh** [comment]
because just doing `oc get pods` gives us perfect logging with pods status, number of restarts ... I think it's useful @kornys

**Comment by lulf** [comment]
Is there not already a `oc describe pods` in `saveKubernetesState` which captures all pod information?

**Comment by famartinrh** [comment]
yes it is @lulf , however in this PR I only had in mind to improve log output, I just was thinking on improve the logging and change that loop we had that only logs pod names and change it with the standard output of `oc get pod`

**Comment by kornys** [comment]
You can get all these information from fabric8 client I guess

**Comment by kornys** [comment]
Anyway lgtm

**Pull request merged**
