### PR TITLE
Upgrade nodejs version v12.18.2 for fixing build/unit test issue

### PR DESCRIPTION
**Pull request by ajaypratap003**
### Type of change

- Enhancement / new feature
- Refactoring

### Description
Reduce version of React and Typescript due to build failed on master.
https://github.com/EnMasseProject/enmasse/pull/4912

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by vbusch** [comment]
I have run the tests for #4912 locally, and they pass with the versions of typescript and react that are currently on master.  The build failures on #4912 do not seem related to these versions.

**Comment by anukritijha** [comment]
> I looked at the failure from #4912 (which I assumed was where the failing build was being reported from)
> 
> ```
> 12:45:45.491 [main] INFO io.enmasse.iot.tenant.impl.AbstractTenantService - Failed to validate trust anchor
> java.lang.NullPointerException: text
> ```
> 
> It doesn't seem related to the typescript / react versions, to me. Is this the build failure you are trying to fix? (Currently unit tests are passing on master).

@vbusch This doesn't seem to be causing the build issue as this exception is there in successful builds as well.

**Comment by ajaypratap003** [comment]
> The unit tests seem to be passing on master currently.
> I believe this commit is for #4912
> Do you know what is in the newer minor versions that would be an issue for that PR?

 These package version causing issue ` "react": "^16.13.1", "typescript": "3.8.3" `

**Comment by obabec** [comment]
@ajaypratap003 Just question don't you need for this specific react and typescript version some newer system wide dependency like npm or something like that? :)

**Pull request merged**
