### PR TITLE
Use podman

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by ctron** [comment]
I think you need to add the following to `.travis.yml`:

~~~yaml
dist: xenial
~~~

As the openjdk PR is merged, this should work now.

**Comment by kornys** [comment]
@lulf I think you need to add `sudo add-apt-repository -y ppa:projectatomic/ppa`

**Comment by kornys** [comment]
@lulf I do not understand why in travis ubuntu /etc/containers/registries.conf is not created by default and on rhel/fedora/centos is created.

**Comment by lulf** [comment]
@kornys because it’s not a standard, and only something that is part of fedora/cent is/rhel

**Comment by lulf** [comment]
Close until we have some spare time to look more into podman

**Pull request closed without merging**
