### PR TITLE
Update to router 1.8.0

### PR DESCRIPTION
**Pull request by grs**

### CODE REVIEW

**Comment by grs** [comment]
@enmasse-ci run tests

**Comment by grs** [comment]
@enmasse-ci run tests

**Comment by grs** [comment]
@enmasse-ci run tests

**Comment by grs** [comment]
@k-wall agreed; updated base (this is the exact same code as rc1, but pulled and built from the final url and tagged accordingly)

**Comment by ctron** [comment]
Looks reasonable to me. I did give it a brief test by replacing the qdr proxy sidecar with the new version, and at least it starts up.

**Pull request merged**
