### PR TITLE
Clean test base unused methods

### PR DESCRIPTION
**Pull request by kornys**
### Type of change

- Refactoring

### CODE REVIEW

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot testcase=io.enmasse.systemtest.iot.isolated.http.HttpAdapterTest

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot testcase=io.enmasse.systemtest.iot.isolated.http.HttpAdapterTest

**Comment by kornys** [comment]
@ctron rebased on master, if iot test pass may I merge it?

**Comment by kornys** [comment]
@enmasse-ci run tests ocp4 profile=iot testcase=io.enmasse.systemtest.iot.isolated.http.HttpAdapterTest test_only

**Pull request merged**
