### PR TITLE
Console test non cluster admin

### PR DESCRIPTION
**Pull request by kornys**

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*WebConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=isolated.web.FirefoxConsoleTest test_only

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=isolated.web.FirefoxConsoleTest test_only

**Pull request merged**
