### PR TITLE
Allow to configure logging of IoT components

### PR DESCRIPTION
**Pull request by ctron**
### Type of change

This allows to configure the logging of IoT components.

- Enhancement / new feature
- Documentation

### Description

This allows not to configure logging on different levels:

* Container level
  * override configuration from config map
  * explicit logback configuration (when logback is being used)
  * explicit logger levels
  * root log level
* Infrastructure level
  * explicit logback configuration (when logback is being used)
  * explicit logger levels
  * root root log level

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [X] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot testcase=io.enmasse.systemtest.iot.isolated.registry.MixedDeviceRegistryTest

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot

**Comment by jbtrystram** [comment]
@ctron that looks awesome, thanks ! Can you add an example in the sample iot config, and add a small section in the documentation ? 
In 5.2.3 iot services configuration example  is wher it would make the most sense IMO

**Pull request merged**
