### PR TITLE
Move to new go

### PR DESCRIPTION
**Pull request by obabec**
### Type of change

- Enhancement / new feature
### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ctron** [comment]
I think you need to update the "go.mod"/"go.sum" file as well

**Comment by obabec** [comment]
@ctron Why? This is just change on installed dependency on our machines. Updating go dependencies have nothing to do with actions I think.

**Comment by obabec** [comment]
@ctron I can surely update go.mod and go.sum too, but I don't want to dig to "your" stuff and just prepare everything so that you can change that any time you want :)

**Comment by ctron** [comment]
> @ctron I can surely update go.mod and go.sum too, but I don't want to dig into "your" stuff and just prepare everything so that you can change that any time you want :)

Its all "our" stuff :grin: … I think it makes sense to switch to the new version in a single PR … @k-wall what do you think?

**Comment by obabec** [comment]
@ctron Ok, I don't have problem with that, I can bump go version here :)

**Comment by ctron** [comment]
Ok, it looks like there is more than just the upgrade … go dependencies are the new NPM hell :roll_eyes: … I will take a look at using Go 1.14 and come back to this PR

**Comment by ctron** [comment]
Ok … so #4974 would do the switch to use Go 1.14

So you've been right, we should have split up things :)

**Comment by obabec** [comment]
@ctron ok cool, I'll revert one commit and this PR should be ready :)

**Comment by kornys** [comment]
@ctron @obabec let me know if you need to merge it ASAP I can merge it before GH actions test complete

**Pull request merged**
