### PR TITLE
TestOpenShiftWithCustomCert robustness improvements

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Bugfix

### Description

TestOpenShiftWithCustomCert robustness improvements

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*brokered.web.*ConsoleTest tests_only crc

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*brokered.web.*ConsoleTest tests_only crc

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*brokered.web.*ConsoleTest tests_only crc

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*brokered.web.*ConsoleTest tests_only crc

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*brokered.web.*ConsoleTest tests_only crc

**Comment by kornys** [comment]
@k-wall just thinking, but this test make changes in cluster right? so maybe these changes should be moved into KubeClusterManager class, this class should contain cluster configurations and allso rollback to original state.

**Comment by k-wall** [comment]
> @k-wall just thinking, but this test make changes in cluster right? so maybe these changes should be moved into KubeClusterManager class, this class should contain cluster configurations and allso rollback to original state.

Good idea. I'll move the code, but as a separate PR to keep the deltas clear.

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*brokered.web.*ConsoleTest tests_only crc

**Comment by kornys** [comment]
@k-wall yes I agree this change to KubeClusterManager should be in different PR. Many thanks

**Pull request merged**
