### PR TITLE
Use new bundle format

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=acceptance

**Comment by kornys** [comment]
@enmasse-ci run tests profile=olm crc

**Comment by kornys** [comment]
@enmasse-ci run tests profile=olm crc

**Comment by kornys** [comment]
@enmasse-ci run tests profile=olm crc

**Comment by kornys** [comment]
@enmasse-ci run tests profile=olm crc

**Comment by kornys** [comment]
@enmasse-ci run tests profile=olm crc

**Comment by lulf** [comment]
@enmasse-ci run tests profile=olm crc

**Comment by lulf** [comment]
@enmasse-ci run tests profile=olm crc

**Comment by lulf** [comment]
@enmasse-ci run tests profile=olm crc

**Review by kornys — APPROVED** [review]

**Pull request merged**
