### PR TITLE
Remove deprecated surefire provider

### PR DESCRIPTION
**Pull request by kornys**

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by lulf** [comment]
Without this, tags won’t behave at all @kornys

**Comment by kornys** [comment]
@lulf i will investigate it, we have to remove this obsolete provider, so there must be a way to run tests with profiles :)

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by kornys** [comment]
@enmasse-ci run tests

**Pull request merged**
