### PR TITLE
Add more verbose logging to debug connectors and frequent reconcile

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci  run tests profile=isolated

**Comment by lulf** [comment]
@enmasse-ci  run tests profile=isolated

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated

**Comment by kornys** [comment]
@lulf is it still actual?

**Pull request closed without merging**
