### PR TITLE
Add router status check for connectors

### PR DESCRIPTION
**Pull request by lulf**
(@k-wall currently based on #3166 but will rebase this once that is merged)

* Refactor and move router status collection into amqp-utils
* Add controller in address-space-controller for checking the router status by querying all routers for an address space looking for the connector and verifying its state.

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
> Looks good. I think what we really desire is the the connector status reports something like "authentication fail" or "no route to host" for a router connector that's failing to make a remote connection, however, I interpret your comment "Until the connector entity allows querying for the status.." means that the router currently doesn't make that information is available, and instead we are having to infer the state of the connector from the absence or otherwise of a connection. I think a feature request against Dispatch Router would be a good idea. What do you think?

@grs WDYT?  Would it be a useful router enhancement to expose the connector's last error via AMQP management?

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
> > Looks good. I think what we really desire is the the connector status reports something like "authentication fail" or "no route to host" for a router connector that's failing to make a remote connection, however, I interpret your comment "Until the connector entity allows querying for the status.." means that the router currently doesn't make that information is available, and instead we are having to infer the state of the connector from the absence or otherwise of a connection. I think a feature request against Dispatch Router would be a good idea. What do you think?
> 
> @grs WDYT? Would it be a useful router enhancement to expose the connector's last error via AMQP management?

https://issues.apache.org/jira/browse/DISPATCH-1419

**Pull request merged**
