### PR TITLE
Handle multiple addresses for purge in a single query

### PR DESCRIPTION
**Pull request by drcoolsanjeev**
### Type of change

- Refactoring

### Description

Modify purge address mutation query and the usage to accept list of addresses.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
@drcoolsanjeev can you rebase (to pickup the API changes in #4547) and trigger `FirefoxConsoleTest#testPurgeAddress`

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest#testPurgeAddress

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest#testPurgeAddress

**Comment by k-wall** [comment]
Above failures appears to be related to the quay.io issues.  Kicked it off again.

**Comment by k-wall** [comment]
rebased against master to pickup defect fix causing the test failures above ^

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest#testPurgeAddress

**Pull request merged**
