### PR TITLE
set message_in/message_out for link routed addresses i.e. topics

### PR DESCRIPTION
**Pull request by grs**
fixes issue #1607

### CODE REVIEW

**Comment by k-wall** [comment]
I'm still seeing the problem.  With a single topic with a single durable subscription, the dashboard still shows me nothing. In addition, I see a Javascript stack trace (both Chrome and Safari).

```
angular.js:14199 TypeError: Cannot read property 'ingress' of undefined
    at saveLastLinkInfo (addresses_ctrl.js:57)
    at calcRates (addresses_ctrl.js:64)
    at addresses_ctrl.js:125
    at Array.forEach (<anonymous>)
    at addresses_ctrl.js:124
    at angular.js:19942
    at f (angular.js:6045)
    at angular.js:6324
(anonymous) @ angular.js:14199
(anonymous) @ angular.js:10707
(anonymous) @ angular.js:19945
f @ angular.js:6045
(anonymous) @ angular.js:6324
setTimeout (async)
k.defer @ angular.js:6322
e @ angular.js:19940
forceDeliveryRateUpdate @ addresses_ctrl.js:123
setTimeout (async)
on_update @ addresses_ctrl.js:156
(anonymous) @ addresses_ctrl.js:170
invoke @ angular.js:4771
R.instance @ angular.js:10592
n @ angular.js:9469
g @ angular.js:8810
(anonymous) @ angular.js:8690
(anonymous) @ angular-ui-router.min.js:7
(anonymous) @ angular.js:1259
sa @ angular.js:10152
n @ angular.js:9551
g @ angular.js:8810
(anonymous) @ angular.js:8690
(anonymous) @ angular.js:9047
l @ angular-ui-router.min.js:7
(anonymous) @ angular-ui-router.min.js:7
$broadcast @ angular.js:18320
(anonymous) @ angular-ui-router.min.js:7
(anonymous) @ angular.js:16696
$eval @ angular.js:17994
$digest @ angular.js:17808
$apply @ angular.js:18102
(anonymous) @ angular.js:26597
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121

```

subsstat1
substats2

**Comment by grs** [comment]
I believe what you are seeing is that when there are no active links for a topic, the message count drops to 0 as at that point the router will no longer have any stats for the associated addresses. This is true also of anycast and multicast addresses. For queues, because they use autolinks, there is always an active link unless the broker is restarted.

This may also not be desirable, but it is I think a distinct issue, affecting all but the queue address type.

**Comment by grs** [comment]
While you have an active link on the topic, you should see messages showing up in the address list and also as part of the pie chart on the dashboard.

screenshot from 2018-09-18 20-28-40

but once you close the links only the queue messages will remain

screenshot from 2018-09-18 20-30-35

a, b, c and d are queue, topic, anycast and multicast respectively

screenshot from 2018-09-18 20-36-53

**Comment by grs** [comment]
@k-wall you were right! I was using subscribers on all addresses when testing. The messages pie chart only counts messages out (not sure what the rationale was there). The messages out from the durable subscription were not being included. I have now updated to fix that as well.

**Pull request merged**
