### PR TITLE
Upgrade Artemis to 2.7.0

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
I'm seeing the following reported by Artemis.  Also it seems Artemis new audit log feature is turned on by default.  It seems quite chatty.


```
2019-03-22T12:14:56.387Z WARN  [ChannelInitializer] Failed to initialize a channel. Closing: [id: 0x0b3424f5]: java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.ssl.OpenSsl
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:204)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:193)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:34)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:188)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:777)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:452)
	at org.apache.activemq.artemis.core.remoting.impl.ssl.SSLSupport.createNettyClientContext(SSLSupport.java:167)
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector.loadOpenSslEngine(NettyConnector.java:680)
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector.access$300(NettyConnector.java:124)
	at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector$1.initChannel(NettyConnector.java:537)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:953)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1461)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:515)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)
```

2019-03-22T12:14:52.618Z INFO  [base] AMQ601014: User anonymous is getting name on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []
2019-03-22T12:14:52.618Z INFO  [base] AMQ601171: User anonymous is getting ID on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []
2019-03-22T12:14:52.619Z INFO  [base] AMQ601014: User anonymous is getting name on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []
2019-03-22T12:14:52.619Z INFO  [base] AMQ601015: User anonymous is getting address on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []
2019-03-22T12:14:52.619Z INFO  [base] AMQ601016: User anonymous is getting filter on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []
2019-03-22T12:14:52.619Z INFO  [base] AMQ601017: User anonymous is getting durable property on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []
2019-03-22T12:14:52.619Z INFO  [base] AMQ601158: User anonymous is getting temporary property on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []
2019-03-22T12:14:52.619Z INFO  [base] AMQ601179: User anonymous is getting purge-on-consumers property on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []
2019-03-22T12:14:52.619Z INFO  [base] AMQ601162: User anonymous is getting consumer count on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []
2019-03-22T12:14:52.619Z INFO  [base] AMQ601178: User anonymous is getting max consumers on target resource: QueueImpl[name=activemq.management, postOffice=PostOfficeImpl [server=ActiveMQServerImpl::serverUUID=fcecf435-4c9b-11e9-b222-0242ac11000f], temp=false]@793b1c1c []

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by lulf** [comment]
I've been able to suppress the audit log. The smoketests pass, but there is some exception in the broker log:

```
2019-03-22T21:42:15.150Z WARN  [ProtonServerReceiverContext] null: java.lang.NullPointerException
        at org.apache.activemq.artemis.core.server.impl.QueueImpl.addTail(QueueImpl.java:898)
        at org.apache.activemq.artemis.core.server.impl.RoutingContextImpl.internalprocessReferences(RoutingContextImpl.java:138)
        at org.apache.activemq.artemis.core.server.impl.RoutingContextImpl.processReferences(RoutingContextImpl.java:133)
        at org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl$2.done(PostOfficeImpl.java:1370)
        at org.apache.activemq.artemis.core.persistence.impl.journal.OperationContextImpl.executeOnCompletion(OperationContextImpl.java:189)
        at org.apache.activemq.artemis.core.persistence.impl.journal.OperationContextImpl.executeOnCompletion(OperationContextImpl.java:130)
        at org.apache.activemq.artemis.core.persistence.impl.journal.AbstractJournalStorageManager.afterCompleteOperations(AbstractJournalStorageManager.java:323)
        at org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl.processRoute(PostOfficeImpl.java:1362)
        at org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl.route(PostOfficeImpl.java:976)
        at org.apache.activemq.artemis.core.postoffice.impl.PostOfficeImpl.route(PostOfficeImpl.java:867)
        at org.apache.activemq.artemis.core.server.impl.ServerSessionImpl.doSend(ServerSessionImpl.java:1972)
        at org.apache.activemq.artemis.core.server.impl.ServerSessionImpl.handleManagementMessage(ServerSessionImpl.java:1857)
        at org.apache.activemq.artemis.core.server.impl.ServerSessionImpl.send(ServerSessionImpl.java:1613)
        at org.apache.activemq.artemis.protocol.amqp.broker.AMQPSessionCallback.serverSend(AMQPSessionCallback.java:510)
        at org.apache.activemq.artemis.protocol.amqp.broker.AMQPSessionCallback.serverSend(AMQPSessionCallback.java:470)
        at org.apache.activemq.artemis.protocol.amqp.proton.ProtonServerReceiverContext.actualDelivery(ProtonServerReceiverContext.java:304)
        at org.apache.activemq.artemis.protocol.amqp.proton.ProtonServerReceiverContext.onMessage(ProtonServerReceiverContext.java:299)
        at org.apache.activemq.artemis.protocol.amqp.proton.AMQPConnectionContext.onDelivery(AMQPConnectionContext.java:541)
        at org.apache.activemq.artemis.protocol.amqp.proton.handler.Events.dispatch(Events.java:92)
        at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.dispatch(ProtonHandler.java:484)
        at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.flush(ProtonHandler.java:284)
        at org.apache.activemq.artemis.protocol.amqp.proton.handler.ProtonHandler.inputBuffer(ProtonHandler.java:241)
        at org.apache.activemq.artemis.protocol.amqp.proton.AMQPConnectionContext.inputBuffer(AMQPConnectionContext.java:170)
        at org.apache.activemq.artemis.protocol.amqp.broker.ActiveMQProtonRemotingConnection.bufferReceived(ActiveMQProtonRemotingConnection.java:149)
        at org.apache.activemq.artemis.integration.amqp.ProtonClientConnectionManager.bufferReceived(ProtonClientConnectionManager.java:107)
        at org.apache.activemq.artemis.core.remoting.impl.netty.ActiveMQChannelHandler.channelRead(ActiveMQChannelHandler.java:73)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1476)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1225)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1272)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at org.apache.activemq.artemis.utils.ActiveMQThreadFactory$1.run(ActiveMQThreadFactory.java:118)

```

**Comment by k-wall** [comment]
Regarding the NPE, I notice that the NPE is thrown on the management message processing path (ServerSessionImpl.handleManagementMessage).  I know Artemis changed this recently https://issues.apache.org/jira/browse/ARTEMIS-1710 so that messages sent to the management address aren't paged.  I wonder if this could be related?

**Comment by lulf** [comment]
@k-wall, it doesn’t seem to print the exception on every management message though. I would expect more of them

**Comment by lulf** [comment]
Also looks like there are some test failures, possibly related?

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by lulf** [comment]
@k-wall So I found at least one issue, which is createQueue management API changed. I've patched agent to add the new parameters, though I'm still seeing some strange agent errors.

**Comment by lulf** [comment]
Need a 2.7.1

**Pull request closed without merging**
