### PR TITLE
Fixed failing monitoring system test

### PR DESCRIPTION
**Pull request by robshelly**
* Fixed bug: systemtest testAddressSpaceRules
* Fixed bug: application monitoring operator not installing on first try
* Fixed bug: monitoring project stuck in terminating state after systemtests

### CODE REVIEW

**Comment by robshelly** [comment]
@lulf Correct, the operator would create these CRDs. However, installing them manually appears[1] to be the workaround implemented to fix the issue of the full monitoring stack not deploying[2].
 
[1] [https://github.com/integr8ly/application-monitoring-operator/blob/master/scripts/install.sh#L26-L37](https://github.com/integr8ly/application-monitoring-operator/blob/master/scripts/install.sh#L26-L37)
[2] [https://github.com/integr8ly/application-monitoring-operator/issues/24](https://github.com/integr8ly/application-monitoring-operator/issues/24)

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/issues/3191

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=MonitoringTest

**Comment by kornys** [comment]
Please look into PR job logs, there is fail "failed to decode...." but iy is not propagated to assert so test result is green.

**Comment by robshelly** [comment]
@enmasse-ci run tests testcase=MonitoringTest

**Pull request merged**
