### PR TITLE
Update to kubernetes-client 4.6.4

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Bugfix

### Description

Taking newer version of kubernetes-client (4.6.4) which will allow some workarounds to be removed from the code-base.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=iot

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTests

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=iot

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=io.enmasse.systemtest.shared.standard.TopicTest,io.enmasse.systemtest.isolated.api.ApiServerTest,io.enmasse.systemtest.isolated.catalog.ServiceCatalogWebTest,io.enmasse.systemtest.isolated.CommonTest

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=io.enmasse.systemtest.shared.standard.TopicTest,io.enmasse.systemtest.isolated.api.ApiServerTest,io.enmasse.systemtest.isolated.catalog.ServiceCatalogWebTest,io.enmasse.systemtest.isolated.CommonTest

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTests

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTest

**Comment by kornys** [comment]
@k-wall you have to use profile smoke to run smoke tests

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Pull request merged**
