### PR TITLE
Allow pr pipeline to run upgrade tests

### PR DESCRIPTION
**Pull request by kornys**

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=brokered.clients.rhea.MsgPatternsInternalTest

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by lulf** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Pull request merged**
