### PR TITLE
Reduce build time dependencies

### PR DESCRIPTION
**Pull request by k-wall**

### CODE REVIEW

**Comment by k-wall** [comment]
Avoid the pulling in (at build time) of unnecessary Artemis dependencies (and its dependencies).  This simplifies EnMasse's build time footprint.  No functional change.

**Comment by k-wall** [comment]
I just use `mvn dependency:tree`

**Comment by k-wall** [comment]
215fecb avoids build time dependencies on a bunch of dependencies of keycloak-services itself (such as Twitter).

**Comment by lulf** [comment]
I was more thinking how you determine which dependencies are only required build time vs run time

**Comment by k-wall** [comment]
> I was more thinking how you determine which dependencies are only required build time vs run time

Nothing fancy.  I was just examining the contents of the Jar artefact produced and reasoning from there.  If we are producing a plugin for a product, then the only classes that need to exist on the class path at compile time are those needed to compile for the plugin.  Everything else is superfluous.  At runtime, it is just the plugin's classes and any dependencies the plugin introduces itself.

**Pull request merged**
