### PR TITLE
Add unit test step for systemtests

### PR DESCRIPTION
**Pull request by obabec**
### Type of change

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by obabec** [comment]
@lulf I am considering if it wouldn't be better to add unit framework step directly to our makefile WDYT ? :-)

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke testcase=brokered.SmokeTest#testAddressTypes test_only

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke testcase=brokered.SmokeTest#testAddressTypes test_only

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke testcase=brokered.SmokeTest#testAddressTypes test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=smoke testcase=brokered.SmokeTest#testAddressTypes

**Pull request merged**
