### PR TITLE
Remove api-server module

### PR DESCRIPTION
**Pull request by lulf**
### Type of change

- Refactoring

### Description

Remove all code related to api-server as well as build system references
to it.

Moves swagger definition to documentation module for the time being, and
add configuration in documentation to replace properties in
swagger.json. Eventually this should be generated from the CRDs.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke

**Comment by kornys** [comment]
@lulf you can also remove creating api-server certs in systemtests OperatorManager.java and in travis, right?

**Comment by lulf** [comment]
@kornys this should be the case already

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated testcase=CommonTest#testMessagingDuringRestartComponents

**Pull request merged**
