### PR TITLE
Iot label job

### PR DESCRIPTION
**Pull request by obabec**
### Type of change

- Enhancement / new feature

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by lulf** [comment]
Do you intend to create a separate flow for IoT? I kind of liked it being part of smoke, unless it adds a lot to the execution time.

**Comment by obabec** [comment]
> Do you intend to create a separate flow for IoT? I kind of liked it being part of smoke, unless it adds a lot to the execution time.
Plan is that this workflow will execute only with iot label. In smoke tests run we will run only IoT acceptance tests :)

**Comment by kornys** [comment]
@obabec close this or do you want to work on it?

**Comment by obabec** [comment]
@kornys I can probably close this, lot of stuff were done so. After minikube is working it will be best to start fresh.

**Pull request closed without merging**
