### PR TITLE
Dlq test ui

### PR DESCRIPTION
**Pull request by obabec**
### Type of change

- Enhancement / new feature

### Description
Tests for DLQ and Expiry features with address creation and data validation using web console. Still in progress. Everything needs to be optimized and refactored once #5173 is merged.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [*] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Review by lulf — DISMISSED** [review]

**Comment by lulf** [comment]
@obabec Can you rebase and run tests?

**Comment by obabec** [comment]
@lulf sure, going to do that ASAP

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest test_only

**Review by kornys — DISMISSED** [review]

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest test_only

**Comment by obabec** [comment]
@enmasse-ci run tests profile=systemtests testcase=isolated.web.FirefoxConsoleTest

**Review by kornys — APPROVED** [review]

**Pull request merged**
