### PR TITLE
Add version and commit revision metadata to operator metadata

### PR DESCRIPTION
**Pull request by lulf**
This allows the operator to be upgraded by applying the new templates,
which will also update any operands like the address space controller,
authentication service and console.

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=upgrade

**Comment by lulf** [comment]
@enmasse-ci run tests profile=upgrade

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by lulf** [comment]
@k-wall We could do that, but it would mean that if a new image for address-space-controller was created with a major.minor tag (but would contain different revision), and it was restarted with the new revision, it would potentially end up auto-restart the router and broker as well, removing the 'choice' of when to do the restart of the messaging infrastructure. However, from what I can tell, it would not apply the new templates unless the infra configs or address space have changed, so it could be it would work as before.

**Comment by k-wall** [comment]
Sorry, I take back my suggestion - I think it makes for confusion.  The revision and version will only ever correspond to the operator's build, this is fine for address space controller/console/authservice since the operator is directly responsible for these deployments.  This is not the case where the admin/route/broker.  If we were to say the rev address space controller image or the standard-controller image. the propagated information would be stale.  It could lead someone to conclude that then update hadn't worked.

I suggest popping off the last commit. Sorry!

**Pull request merged**
