### PR TITLE
Replace statefulset if volumeclaimtemplate has changed

### LINKED ISSUE #3144: Infraconfig-triggered volume resize does not work on Kubernetes 1.15
**Describe the bug**
On Kubernetes 1.15, when using a storage provider that supports resizing, changing the broker storage configuration and setting applyPersistentVolumeClaim: true in the standard infra config causes the standard-controller failing to patch the statefulset of the broker:

**To Reproduce**
1. Deploy EnMasse on Kubernetes 1.15
2. Run the standard.infra.InfraTest#testDecrementInfra systemtest
3. Observe test failure

**Expected behavior**
Changes should be applied

**Additional context**

Log of standard-controller:

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://172.30.0.1/apis/apps/v1/namespaces/amq-online-images/statefulsets/broker-iha99cy4q7-z9qi. Message
: StatefulSet.apps "broker-iha99cy4q7-z9qi" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden. Receive
d status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec, message=Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', a
nd 'updateStrategy' are forbidden, reason=FieldValueForbidden, additionalProperties={})], group=apps, kind=StatefulSet, name=broker-iha99cy4q7-z9qi, retryAfterSeconds=null, uid=null, additio
nalProperties={}), kind=Status, message=StatefulSet.apps "broker-iha99cy4q7-z9qi" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and '
updateStrategy' are forbidden, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```

### PR DESCRIPTION
**Pull request by lulf**
Fixes #3144

### CODE REVIEW

**Comment by famartinrh** [comment]
LGTM, can't run tests on ocp4 in a PR so if you agree once merged I can test it in our ocp 4.2

**Comment by famartinrh** [comment]
however we can just run it also in ocp 3.11, just to make sure anything is broken

**Comment by famartinrh** [comment]
@enmasse-ci run tests testcase=**.InfraTest

**Comment by lulf** [comment]
I will add a unit test as well

**Comment by lulf** [comment]
@k-wall @famartinrh added unit test and fixed the brokered case as well

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=**.InfraTest

**Pull request merged**
