### PR TITLE
New upgrade test

### PR DESCRIPTION
**Pull request by kornys**

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade upgrade_from=0.26.5

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade upgrade_from=0.26.5

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@lulf nope, it still fails after upgrade on non existing addressspaces... I have to investigate that

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@lulf I fixed problems in this test with upgrade/downgrade -> I was by mistake run ansible with bad namespace. But anyway Upgrade upgrades only api-server, keycloak init image and service broke but it is a same like on master so check image upgraded fail on that.

**Comment by lulf** [comment]
@kornys latest commit on master should fix it

**Comment by kornys** [comment]
@lulf ok I will rebase and try it

**Comment by kornys** [comment]
@enmasse-ci run tests profile=systemtests-upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=upgrade

**Comment by kornys** [comment]
@enmasse-ci run tests profile=upgrade

**Pull request merged**
