### PR TITLE
bump infinispan to latest productised version

### PR DESCRIPTION
**Pull request by jbtrystram**
### Type of change

- Enhancement / new feature

### Description

Update infinispan to 9.4.17

### Checklist

- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by jbtrystram** [comment]
@enmasse-ci run tests profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by jbtrystram** [comment]
@enmasse-ci run tests profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by jbtrystram** [comment]
@enmasse-ci run tests profile=iot

**Pull request merged**
