### PR TITLE
prevent HTTP and AMQP tenant endpoints in Infinispan DR

### PR DESCRIPTION
**Pull request by jbtrystram**
Signed-off-by: Jean-Baptiste Trystram <jbtrystram@redhat.com>

### CODE REVIEW

**Comment by jbtrystram** [comment]
@ctron I thought it could be added as a "modularity" feature in hono, using `@conditionnalOnProperty` or something similar in [org.eclipse.hono.deviceregistry.ApplicationConfig](https://github.com/eclipse/hono/blob/master/services/device-registry/src/main/java/org/eclipse/hono/deviceregistry/ApplicationConfig.java)

**Comment by jbtrystram** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
So that would only enable the tenant endpoints when the `CacheTenantService` bean is present?

**Comment by jbtrystram** [comment]
yes. It have the desired effect from what I tested : 
```
14:44:39.957 [main] INFO  i.e.i.r.i.InfinispanRegistry$$EnhancerBySpringCGLIB$$3abf1492 - Starting authentication service DelegatingAuthenticationService[Authentication service: localhost:35672]
14:44:39.959 [main] INFO  i.e.i.r.i.InfinispanRegistry$$EnhancerBySpringCGLIB$$3abf1492 - Starting registration service io.enmasse.iot.registry.infinispan.CacheRegistrationService@45e6d1e0
14:44:39.959 [main] INFO  i.e.i.r.i.InfinispanRegistry$$EnhancerBySpringCGLIB$$3abf1492 - Starting credentials service io.enmasse.iot.registry.infinispan.CacheCredentialService@4da1f38a
14:44:39.961 [vert.x-eventloop-thread-0] INFO  o.e.h.s.a.BaseAuthenticationService - listening on event bus [address: authentication.in] for authentication requests
14:44:39.961 [vert.x-eventloop-thread-1] INFO  i.e.i.r.i.CacheRegistrationService - listening on event bus [address: registration.in] for requests
14:44:39.961 [vert.x-eventloop-thread-2] INFO  i.e.i.r.i.CacheCredentialService - listening on event bus [address: credentials.in] for requests
14:44:39.969 [vert.x-eventloop-thread-3] INFO  o.e.h.d.DeviceRegistryAmqpServer - using OpenTracing Tracer implementation [io.opentracing.noop.NoopTracerImpl]
14:44:39.976 [vert.x-eventloop-thread-3] INFO  o.e.h.s.r.RegistrationAmqpEndpoint - using OpenTracing Tracer implementation [io.opentracing.noop.NoopTracerImpl]
14:44:39.978 [vert.x-eventloop-thread-3] INFO  o.e.h.s.c.CredentialsAmqpEndpoint - using OpenTracing Tracer implementation [io.opentracing.noop.NoopTracerImpl]
14:44:39.978 [vert.x-eventloop-thread-3] DEBUG o.e.h.d.DeviceRegistryAmqpServer - registering endpoint [registration]
14:44:39.978 [vert.x-eventloop-thread-3] DEBUG o.e.h.d.DeviceRegistryAmqpServer - registering endpoint [credentials]
14:44:39.979 [vert.x-eventloop-thread-6] INFO  o.e.h.d.DeviceRegistryAmqpServer - Vertx native support: false
14:44:39.979 [vert.x-eventloop-thread-6] DEBUG o.e.h.config.ServiceConfigProperties - neither key/cert nor keystore is configured
14:44:39.979 [vert.x-eventloop-thread-6] WARN  o.e.h.d.DeviceRegistryAmqpServer - Secure port number configured, but the certificate setup is not correct. No secure port will be opened - please check your configuration!
14:44:39.979 [vert.x-eventloop-thread-6] INFO  o.e.h.d.DeviceRegistryAmqpServer - starting endpoint [name: credentials, class: org.eclipse.hono.service.credentials.CredentialsAmqpEndpoint]
14:44:39.979 [vert.x-eventloop-thread-6] INFO  o.e.h.d.DeviceRegistryAmqpServer - starting endpoint [name: registration, class: org.eclipse.hono.service.registration.RegistrationAmqpEndpoint]
14:44:39.979 [vert.x-eventloop-thread-6] DEBUG o.e.h.config.ServiceConfigProperties - neither key/cert nor keystore is configured
14:44:39.979 [vert.x-eventloop-thread-6] INFO  o.e.h.d.DeviceRegistryAmqpServer - secure port is not enabled
14:44:39.981 [vert.x-eventloop-thread-3] INFO  o.e.h.d.DeviceRegistryRestServer - using OpenTracing Tracer implementation [io.opentracing.noop.NoopTracerImpl]
14:44:39.985 [vert.x-eventloop-thread-7] INFO  o.e.h.d.DeviceRegistryRestServer - Vertx native support: false
14:44:39.985 [vert.x-eventloop-thread-7] DEBUG o.e.h.config.ServiceConfigProperties - neither key/cert nor keystore is configured
14:44:39.986 [vert.x-eventloop-thread-7] INFO  o.e.h.d.DeviceRegistryRestServer - limiting size of inbound request body to 2048 bytes
14:44:39.991 [vert.x-eventloop-thread-7] INFO  o.e.h.d.DeviceRegistryRestServer - starting endpoint [name: credentials, class: org.eclipse.hono.service.credentials.CredentialsHttpEndpoint]
14:44:39.991 [vert.x-eventloop-thread-7] INFO  o.e.h.d.DeviceRegistryRestServer - starting endpoint [name: registration, class: org.eclipse.hono.service.registration.RegistrationHttpEndpoint]
14:44:39.992 [vert.x-eventloop-thread-7] DEBUG o.e.h.config.ServiceConfigProperties - neither key/cert nor keystore is configured
14:44:40.066 [vert.x-eventloop-thread-7] WARN  o.e.h.d.DeviceRegistryRestServer - server listens on non-standard insecure port [0.0.0.0:28080], default is 8080
14:44:40.066 [vert.x-eventloop-thread-6] WARN  o.e.h.d.DeviceRegistryAmqpServer - server listens on non-standard insecure port [0.0.0.0:25672], default is 5672
14:44:40.066 [vert.x-eventloop-thread-3] INFO  o.e.h.s.a.d.DelegatingAuthenticationService - registering readiness check using vert.x Address Resolver
14:44:40.068 [vert.x-eventloop-thread-3] INFO  o.e.h.s.VertxBasedHealthCheckServer - readiness probe available at http://0.0.0.0:8088/readiness
14:44:40.068 [vert.x-eventloop-thread-3] INFO  o.e.h.s.VertxBasedHealthCheckServer - liveness probe available at http://0.0.0.0:8088/liveness
14:44:40.069 [main] INFO  i.e.i.r.i.InfinispanRegistry - Started InfinispanRegistry in 1.943 seconds (JVM running for 2.471)
```

**Comment by jbtrystram** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by jbtrystram** [comment]
@enmasse-ci run tests profile=shared-iot

**Pull request merged**
