### PR TITLE
Bump fabric8 kubernetes-client from 4.1.3 to 4.6.2

### PR DESCRIPTION
**Pull request by k-wall**
This allows the workaround #2999 to be removed.

Also:
* Bump sundrio.version from 0.16.4 to 0.17.2
* Remove KubernetesDeserializer thread safety workaround.

### CODE REVIEW

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTests

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTests

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTests

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTests

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTests

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTests

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by k-wall** [comment]
I see unreliability related to cascading delete of the admin deployment.  It seems sometimes the admin pod is being left behind after the deployment is delete, suggesting incorrect DeleteOptions.  However, I've been unable to find the code path that is causing this, and the problem seems to be sporadic.   I need to look at the implementation of the library itself.

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTests

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=SmokeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=shared

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=FirefoxWebConsoleTest,ServiceCatalogWebTest,CustomResourceDefinitionAddressesTest,CommonTest

**Comment by k-wall** [comment]
@lulf I believe this is good to be merged, if you could review the additional changes.

**Pull request merged**
