### PR TITLE
Remove fsgroup fallback for standard authservice

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=io.enmasse.systemtest.olm.OLMDefaultTest#testExampleResourcesSameNamespaceAsOperator olm

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=io.enmasse.systemtest.olm.OLMDefaultTest OLM

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=io.enmasse.systemtest.olm.OLMDefaultTest OLM

**Comment by lulf** [comment]
@k-wall Yeah, it could still be useful for clusters where there are some explicit restrictions set up.

**Pull request merged**
