### PR TITLE
Fix deployment of secrets for plain Kubernetes

### PR DESCRIPTION
**Pull request by ctron**
### Type of change

- Bugfix

### Description

This fixes the missing secrets for the device registry, when testing on plain kubernetes.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ctron** [comment]
@enmasse-ci run tests ocp4 profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by kornys** [comment]
@ctron if you use beforeall, you need to apply same workaround as we apply here -> https://github.com/EnMasseProject/enmasse/blob/f3eed1fbedf3250baa4f6b18944407d47638c7d7/systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java#L96 where you need to catch exception and raise it in before each. it is a workaround until they release new surefire plugin version  with fix.

**Comment by kornys** [comment]
@ctron and also you triggered jenkins with wrong test, seem io.enmasse.systemtest.iot.shared.http.HttpAdapterTest no longer exists

**Comment by ctron** [comment]
> @ctron and also you triggered jenkins with wrong test, seem io.enmasse.systemtest.iot.shared.http.HttpAdapterTest no longer exists

Indeed … it got moved recently. Still, everything is green :grin:

**Comment by ctron** [comment]
> @ctron if you use beforeall, you need to apply same workaround as we apply here ->
> 
> https://github.com/EnMasseProject/enmasse/blob/f3eed1fbedf3250baa4f6b18944407d47638c7d7/systemtests/src/main/java/io/enmasse/systemtest/listener/JunitCallbackListener.java#L96
> where you need to catch exception and raise it in before each. it is a workaround until they release new surefire plugin version with fix.

Is that really necessary? This is an interface, extending a test case. But not a "test extension". And the `JunitCallbackListener` should still be in play.

**Comment by kornys** [comment]
@ctron anyway if some exception is thrown in beforeall method, test is not triggered and also surefire report that as green because of issue in surefire plugin

**Comment by ctron** [comment]
@kornys I added a aroundaround

**Comment by kornys** [comment]
@ctron thank you, looks really good

**Pull request merged**
