### PR TITLE
Re-enable command and control test

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests testcase=**.iot.** profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by famartinrh** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Pull request merged**
