### PR TITLE
Skip button to select provider to login with

### PR DESCRIPTION
**Pull request by lulf**
As there is only 1 provider present, there is no point in adding the
extra level of indirection.

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by lulf** [comment]
@k-wall Is there any reason for not setting this option?

@kornys Probably tests need to be modified to not expect this page, right?

**Comment by kornys** [comment]
@lulf probably yes, do you have images somewhere with this change? I will test it

**Comment by lulf** [comment]
@kornys docker.io/lulf/console-init:latest

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by kornys** [comment]
@enmasse-ci run tests profile=isolated testcase=FirefoxConsoleTest

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated

**Comment by kornys** [comment]
@enmasse-ci run tests profile=isolated

**Comment by kornys** [comment]
@lulf seems my “fix” broke web tests I have to check it later

**Comment by kornys** [comment]
@enmasse-ci run tests profile=isolated testcase=FirefoxConsoleTest

**Pull request merged**
