### PR TITLE
Fix Kubernetes annotation to match all kube cluster imlementation

### PR DESCRIPTION
**Pull request by kornys**
### Type of change

- Bugfix

### Description

Allow to match all kubernetes implementation not only minikube

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@lulf @obabec I tested it with ocp and microk8s and it works, so from now tests marked with `@Kubernetes` annotation will run on all kube implemnetations except ocp, `@Kubernetes(type = ClusterType.Minikube)` will enable tests only on minikube for example.

**Comment by kornys** [comment]
@lulf im not sure if this failed test in pr ever worked because it has never beed triggered in pr because of wrong kubrnetes detection

**Comment by lulf** [comment]
@kornys Yeah, thats what I'm thinking to. I'm looking into it.

**Comment by kornys** [comment]
@lulf so do you agree with merging this PR?

**Comment by kornys** [comment]
@lulf @obabec job passed so can I merge it?

**Comment by lulf** [comment]
@kornys Looks to me like this causes OpenShift to run tests annotated with Kubernetes as well. Should we have a way to specify Kubernetes-only?

**Pull request merged**
