### PR TITLE
remove unnecessary sleep in AddressUtils

### PR DESCRIPTION
**Pull request by famartinrh**

### CODE REVIEW

**Comment by lulf** [comment]
@kornys ok to merge?

**Comment by kornys** [comment]
@enmasse-ci run tests profile=shared test_only testcase=standard.**

**Comment by kornys** [comment]
@lulf let's wait for results please

**Comment by famartinrh** [comment]
@enmasse-ci run tests profile=shared test_only testcase=standard.**

**Comment by lulf** [comment]
@famartinrh does the test failures indicate that sleeps are needed or not? :)

**Comment by famartinrh** [comment]
sorry I just forgot about this PR , @lulf given that only 2 tests failed I would say the sleeps are not needed

**Pull request merged**
