### PR TITLE
Supress download logging maven

### PR DESCRIPTION
**Pull request by kornys**

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke test_only

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke test_only

**Comment by lulf** [comment]
@kornys I didn't realize this would affect running tests locally as well. I think we shouldn't require everyone to upgrade to maven 3.6 in order to run tests at all.

**Comment by kornys** [comment]
@lulf hmmm, I think it is ok to require latest tool version, anyway I will open an PR

**Comment by kornys** [comment]
#3488

**Comment by lulf** [comment]
@kornys IMO the rule of thumb is what is available in latest package managers :) maybe it can be detected by script?

**Comment by lulf** [comment]
@kornys alternatively add an environment variable that CI can pass?

**Comment by gemmellr** [comment]
You shouldn't hammer the Apache archive by downloading maven from it on every build.

You could use the travis cache (https://docs.travis-ci.com/user/caching/) to avoid re-downloading it every time (which could similarly apply to deps themselves even without this PR).

You could also get it from maven central (http://repo2.maven.org/maven2/org/apache/maven/apache-maven/3.6.2/apache-maven-3.6.2-bin.zip).

Or best of all, both.

**Comment by kornys** [comment]
@gemmellr thanks! will fix that

**Pull request merged**
