### PR TITLE
Fix sniped tests

### PR DESCRIPTION
**Pull request by kornys**
fix snipped tests which failed on upstream/downstream

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest#testAddressSpaceSnippetStandard+testAddressSnippetStandard+testAddressSpaceSnippetBrokered+testAddressSnippetBrokered test_only

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest#testAddressSpaceSnippetStandard+testAddressSnippetStandard+testAddressSpaceSnippetBrokered+testAddressSnippetBrokered test_only

**Comment by lulf** [comment]
Why was this failing test merged?

**Comment by obabec** [comment]
> Why was this failing test merged?

That test is failing because of race condition that we've already discussed. Also test wasn't failing when it was merged :) This is just fix for other snippet tests.

**Pull request merged**
