### PR TITLE
Add support for setting affinity, tolerations, priorityclass and labels on infra configs

### PR DESCRIPTION
**Pull request by lulf**
@vbusch @k-wall As per #2474 the new fields are added to the schema and applied by the infra configs. I will add a few unit tests as well, but there is 1 systemtest with some basic validation.

@kornys @famartinrh Let me know if the systemtest changes look ok

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=InfraTest

**Comment by kornys** [comment]
@lulf I didn't see any update for StandardInfraConfigSpecBrokerBuilder in systemtests? is this change only for brokered address space?

**Comment by lulf** [comment]
@kornys I will add it, just want your comments on the general approach

**Comment by kornys** [comment]
@lulf aha ok :) so I would like to have a help method for PodTemplateSpecBuilder like we have for Plans, AddressSpace, Addresses etc... otherwise it looks good to me

**Comment by lulf** [comment]
@kornys Added systemtests for standard, and for all 'components' in each address space + utility for creating template spec.

**Comment by kornys** [comment]
@lulf thanks, and could you move createTemplateSpec into PlansUtils.java? :)

**Comment by lulf** [comment]
@kornys Done

@k-wall @vbusch added unit tests as well now.

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=InfraTest

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=InfraTest

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=InfraTest

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=InfraTest

**Pull request merged**
