### PR TITLE
Replaces Glide with Go Modules

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

Refactoring, replace Glide with Go Modules.

### Description

Replaces Glide with Go Modules.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
I have one outstanding problem with verify/update codegen.  The issue is that the vendoring with `go mod` doesn't copy non-go packages files, so neither generate-groups.sh nor the mains (`cmd/deepcopy-gen/main.go`) get copied to the vendor tree.  This seems to be by design.

To workaround, I think I need to have the Travis file install code-gen and generate-groups.sh.  @lulf @ctron perhaps you see an easier way?

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=smoke

**Comment by ctron** [comment]
:+1: In general for this … more like :fireworks: :tada: :1st_place_medal:  … I really hope this makes Go dependencies a little less painful.

Is there a reason why you chose kubernetes 1.14.1 rather than e.g. 1.14.9?

**Comment by k-wall** [comment]
> 👍 In general for this … more like 🎆 🎉 🥇 … I really hope this makes Go dependencies a little less painful.
> 
> Is there a reason why you chose kubernetes 1.14.1 rather than e.g. 1.14.9?

The contents of the `replaces` section in the go.mod came from https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#modules-3 .  It used 1.14.1. I did notice that glide was configured to use 1.14.9 and spent quite a lot of time trying to identify a equivalent consistent replaces set for 1.14.9 but hit problem after problem trying to get to a working configuration.

**Comment by k-wall** [comment]
Clicked close by mistake.

**Comment by k-wall** [comment]
The failing Smoke tests are down to the operator failing to create the address-space-controller.  Just trying to get to the bottom of this issue


`{"level":"info","ts":1574119311.7867115,"logger":"cmd","msg":"Registering components..."}
{"level":"info","ts":1574119311.8622484,"logger":"controller_address_space_controller","msg":"Reconciling Address Space Controller","Request.Namespace":"enmasse-infra","Request.Name":"address-space-controller"}
{"level":"error","ts":1574119311.862407,"logger":"controller_address_space_controller","msg":"Error creating address space controller deployment","Request.Namespace":"enmasse-infra","Request.Name":"address-space-controller","error":"the cache is not started, can not read objects","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/cloud-user/jenkins/workspace/enmasse-master-folder/enmasse-pr/enmasse/go/src/github.com/enmasseproject/enmasse/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/enmasseproject/enmasse/pkg/controller/address_space_controller.(*ReconcileAddressSpaceController).Reconcile\n\t/home/cloud-user/jenkins/workspace/enmasse-master-folder/enmasse-pr/enmasse/go/src/github.com/enmasseproject/enmasse/pkg/controller/address_space_controller/controller.go:120\ngithub.com/enmasseproject/enmasse/pkg/controller/address_space_controller.add\n\t/home/cloud-user/jenkins/workspace/enmasse-master-folder/enmasse-pr/enmasse/go/src/github.com/enmasseproject/enmasse/pkg/controller/address_space_controller/controller.go:87\ngithub.com/enmasseproject/enmasse/pkg/controller/address_space_controller.Add\n\t/home/cloud-user/jenkins/workspace/enmasse-master-folder/enmasse-pr/enmasse/go/src/github.com/enmasseproject/enmasse/pkg/controller/address_space_controller/controller.go:61\ngithub.com/enmasseproject/enmasse/pkg/controller.AddToManager\n\t/home/cloud-user/jenkins/workspace/enmasse-master-folder/enmasse-pr/enmasse/go/src/github.com/enmasseproject/enmasse/pkg/controller/controller.go:19\nmain.main\n\t/home/cloud-user/jenkins/workspace/enmasse-master-folder/enmasse-pr/enmasse/go/src/github.com/enmasseproject/enmasse/cmd/controller-manager/main.go:72\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
`

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=smoke

**Comment by k-wall** [comment]
@enmasse-ci run tests

**Comment by k-wall** [comment]
> This means we can get rid of GOPATH and the tricks we do there for travis and in our makefiles right? (Though I'm not advocating for doing that in this PR). Thanks for doing the heavy lifting ;)

@lulf i hope so, I agree let's leave the tidy up for a separate PR.

**Pull request merged**
