### PR TITLE
Escape forbidden chars in filters

### PR DESCRIPTION
**Pull request by anukritijha**
### Type of change

- Bugfix

### Description

This PR adds the following functionalities:
- Escape forbidden chars in all the filters
- Remove escape characters from filter chips
- Remove Title from Edit Dialog of Address Space
- Remove warnings from Filter components
- Remove unwanted console logs

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by anukritijha** [comment]
Fix: #4280

**Comment by anukritijha** [comment]
https://github.com/EnMasseProject/enmasse/pull/4278#issuecomment-610813280

**Comment by anukritijha** [comment]
image

**Comment by anukritijha** [comment]
image

**Comment by anukritijha** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest crc

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Pull request merged**
