### PR TITLE
Use phase instead of isReady

### PR DESCRIPTION
**Pull request by lulf**
This is missing the use of colors for the different phases.

### CODE REVIEW

**Comment by kornys** [comment]
this will brake tests I guess

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=common.console.**

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=common.console.**

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=common.console.**

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=common.console.**

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=common.console.**

**Pull request merged**
