### PR TITLE
Generate template assembly archive

### PR DESCRIPTION
**Pull request by lulf**
### Type of change

- Refactoring

### Description

This also changes the name of the assembly bundle from enmasse-${TAG} to
enmasse-${VERSION}, which will be different for master (i.e pom version
instead of tag which defaults to 'latest'). CI environments need to
accomodate this change.

Generating a dist zip will allow deploying the template as a maven
artifact.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@lulf it will require small upstream CI update but large dowstream CI update :-)

**Comment by lulf** [comment]
@kornys Sorry, I think we need to cope with that change. I'd like to avoid keeping the tag around just for CI.

**Comment by kornys** [comment]
@lulf no no I think it is good change, I just noted that to keep it in mind

**Comment by lulf** [comment]
@kornys With the latest changes, I think maybe we don't need to change CI after all.

**Comment by lulf** [comment]
@enmasse-ci run tests profile=smoke

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke test_only

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke test_only

**Pull request merged**
