### PR TITLE
Bump gqlgen from v0.10.2 => v0.11.3

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Enhancement / new feature

### Description

Bump gqlgen from v0.10.2 => v0.11.3.   No functional changes from an end-user perspective.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Comment by jbtrystram** [comment]
@k-wall is this test failure due to an infrastructure issue ?

**Comment by k-wall** [comment]
> @k-wall is this test failure due to an infrastructure issue ?

that test failure was #3970. It is not related.

**Pull request merged**
