### PR TITLE
Add proper error when tenant is in an invalid format

### PR DESCRIPTION
**Pull request by ctron**

### CODE REVIEW

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by kornys** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=shared-iot

**Pull request merged**
