### PR TITLE
Fix #5226: Chunk address/connection stats processing work

### LINKED ISSUE #5226: Address/connection stats processing may block event loop for excessive periods of time
**Describe the bug**

For deployments with large numbers of addresses/connections, the volume of stats data may be sufficient to block the NodeJS event loop for excessive periods of time.  This means other processing activities may be delayed.  This may include the timely processing of Kubernetes probes where a delayed response can lead to spurious probe failures and container restarts.

The issue is the address and connection stats data is processed in one go, without yielding control back to the event loop.  In a busy system, say with lots of active connections, there will be significant work generating/handling the `update` events.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Bugfix

### Description

Chunk address/connection stats processing work in order to avoid the risk that the NodeJS event loop will be block for an unacceptable length of time.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Review by vbusch — DISMISSED** [review]
LGTM

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated

**Review by vbusch — DISMISSED** [review]

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated

**Comment by k-wall** [comment]
@enmasse-ci run tests ocp4

**Comment by k-wall** [comment]
@enmasse-ci run tests ocp4

**Comment by k-wall** [comment]
@enmasse-ci run tests ocp4

**Review by vbusch — APPROVED** [review]
LGTM

**Comment by k-wall** [comment]
@enmasse-ci run tests ocp4

**Pull request closed without merging**
