### PR TITLE
Avoid reliance of deprecated service-ca.crt (OpenShift4)

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Enhancement / new feature

### Description

Avoid reliance of deprecated service-ca.crt (OpenShift 4).  On OpenShift 3.11, the existing behaviour must be maintained.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated

**Comment by zschwarz** [comment]
@enmasse-ci run tests profile=isolated

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated ocp4

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated ocp4

**Review by rgodfrey — APPROVED** [review]
LGTM (for what it's worth)

**Pull request merged**
