### PR TITLE
[systemtests] console server test

### PR DESCRIPTION
**Pull request by kornys**
### Type of change

- Enhancement / new feature

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@famartinrh rebased and cherry-picked on actual console-server branch. Closing old PR

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=web.**

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=web.**

**Comment by famartinrh** [comment]
@enmasse-ci run tests testcase=web.**

**Comment by famartinrh** [comment]
@enmasse-ci run tests testcase=io.enmasse.systemtest.shared.standard.web.FirefoxConsoleTest#testSortAddressesBySenders

**Comment by famartinrh** [comment]
@enmasse-ci run tests testcase=web.**

**Comment by kornys** [comment]
@enmasse-ci run tests testcase=web.**

**Comment by lulf** [comment]
@kornys Can we delete it?

**Pull request closed without merging**
