### PR TITLE
Refactor device registry to prepare for JDBC based implementation

### PR DESCRIPTION
**Pull request by ctron**
### Type of change

- Enhancement / new feature
- Refactoring

### Description

Prepare for JDBC based device registry.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot testcase=io.enmasse.systemtest.iot.shared.http.HttpAdapterTest

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot testcase=io.enmasse.systemtest.iot.isolated.registry.InfinispanDeviceRegistryTest

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Comment by jbtrystram** [comment]
@ctron nice work ! Looks like the `iot-device-registry-base` package could be contributed in hono to have a base for an easy implementation with any key;value store :) 

Would it make sense to have `DeviceKey` and similar classes to extend the ones in `iot-device-registry-base`.

Thanks for adding the skeleton for the jdbc implementation :)

**Comment by ctron** [comment]
@enmasse-ci run tests profile=iot

**Pull request merged**
