### PR TITLE
Add k8s loadBalancer instead of route when not on openshift

### PR DESCRIPTION
**Pull request by jbtrystram**
### Type of change

- Bugfix
- Enhancement / new feature

### Description

When not on openshift, a kubernetes loadbalancer should be used. This is a first draft to add this in iot compenents.

@lulf there are still a few types errors here and there but I wanted your feedback on the general approach. WDYT ? 
Aslo, according to [1] we need an Ingress controller. Any opinion on which one we should use ? 

[1]: https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by obabec** [comment]
Before testing function of these change this branch should be rebased on newer master with changed deployment of infinispan on kubernetes.

**Comment by lulf** [comment]
Can this be rebased and reviewed?

**Comment by jbtrystram** [comment]
@lulf @obabec it looks like @ctron already added it https://github.com/EnMasseProject/enmasse/blob/0da533e3b0e0d83bfaf8dcb5793b83da44c59bff/pkg/controller/iotconfig/device_registry.go#L175

**Comment by ctron** [comment]
IIRC it was @dejanb 

However, I think the misses the update of the status section

**Pull request closed without merging**
