### PR TITLE
updated dynamic_resources.sh & partitionPV.sh from the latest cct_module

### PR DESCRIPTION
**Pull request by vbusch**
Must be merged along with EnMasseProject/java-docker-base

### CODE REVIEW

**Comment by vbusch** [comment]
@lulf , which build is responsible for pushing the java-docker-base to https://hub.docker.com/r/enmasseproject/java-base/tags/ ?
This commit requires the changes to https://github.com/EnMasseProject/java-docker-base/pull/2
And I am worried that the changes to java-base, will start giving people trouble if this pr doesn't go through.

**Comment by lulf** [comment]
@vbusch It is built manually. I just pushed a new version of the image, but you need to update the Dockerfiles in this PR branch to use the new version (8-4).

**Comment by vbusch** [comment]
@lulf Thank you.  I updated the versions.  Can you merge it?  I will then commit the equivalent changes downstream.

**Comment by lulf** [comment]
@vbusch Done. Thanks for updating the scripts!

**Pull request merged**
