### PR TITLE
Prefix agent/broker reply-to address with "activemq.management"

### PR DESCRIPTION
**Pull request by k-wall**

### CODE REVIEW

**Comment by lulf** [comment]
This needs to be fixed in standard controller as well which checks queue message counts as part of checking if an address is drained on a broker. Would that complicate cleanup of those queues?

**Comment by k-wall** [comment]
> This needs to be fixed in standard controller as well which checks queue message counts as part of checking if an address is drained on a broker. Would that complicate cleanup of those queues?

Yes, indeed, ProtonRequestClient would need the same 'fix'.   Agent's synch process will take care of deleting the old response queues.  Attempts to delete live response queues will fail as they have a receiver link attached which Artemis disallows.  You actually already see Agent sync trying and failing to delete dynamic response queues today, so in this respect, it is no worse.

**Comment by k-wall** [comment]
I tried making changes to StandardController.  I wasn't happy with the results.  The complexity was sending the request for the removal of your response queue when you still have a receiving link attached to the queue.   I tried a couple of approaches (sending a one shot request, closing the receiving link first), but the code was displeasing.   Also the risk of queue cleanup going wrong and queues accumulating was troubling.   This would create a bigger problem than the one I am trying to solve.

On balance I think leaving standard-controller as it stands is better.  If a broker that is being drained is full and the depth query fails, the upshot is the BrokerStatusCollector assumes it is not ready for removal.  This is safe.  Once the application drains the queue a but, the depth queries will start to work again.  We can live with the noise in the logs.  If  ARTEMIS-2262 gets implemented, we can revisit.

I do think the changes for agent are worth having.  Currently the user's ability to control addresses when the broker is full will be impaired by the defect.

**Comment by k-wall** [comment]
The agent now uses Artemis management to create a non-durable, purge on no consumers, exclusive reply-to queue named `activemq.management.tmpreply.<uuid>`.  Old response queues will be cleaned up either by the action of the address synch (which deletes for queues so named with 0 consumers attached), or Broker restart.  The `purgeOnNoConsumers` is belt and braces. - it simple ensures unconsumed management responses are purged as soon as possible.

I updated the original issue #2366 with a description of the issue from the messaging tenant perspective.  We ought to add a system test ensuring the system behaviours problem under the broker full boundary condition. This should be easy now we have the convenient ability to control the global-max-size.

**Comment by lulf** [comment]
@enmasse-ci run tests

**Pull request merged**
