### PR TITLE
Remove !!GLOBAL_DLQ

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Enhancement / new feature

### Description

Removes unused configuration.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated

**Comment by vbusch** [comment]
@enmasse-ci run tests profile=isolated

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=isolated

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance

**Pull request closed without merging**
