### PR TITLE
Do not merge - investigation 504 gateway timeout on console login

### PR DESCRIPTION
**Pull request by k-wall**
openshift oauth-proxy image switched to k_wall/oauth-proxy:latest (debug added)

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*WebConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
Raised https://github.com/openshift/oauth-proxy/pull/162 to allow the OpenShift's Providers HTTP request timeout to be configured.

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest test_only

**Comment by lulf** [comment]
@k-wall Is it ok to close this for now?

**Comment by k-wall** [comment]
Closing, the problem has seemed to stop manifesting at the moment.  Also the change to OpenShift OAuthProxy is accepted, so once there is a release we should have a clearer error message if the problem recurs.

**Pull request closed without merging**
