### PR TITLE
Remove iot and shared infra

### PR DESCRIPTION
**Pull request by lulf**
Based on #5113, needs to be rebased once that is merged.

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=acceptance

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by lulf** [comment]
@enmasse-ci run tests profile=Isolated

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by lulf** [comment]
@enmasse-ci run tests profile=acceptance

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by garyedwards** [comment]
Hi @lulf what are the plans for IoT / Hono component support within the Enmasse project?  If these are important to us should we look to the official Hono distros moving forward?

Thanks for your work on this great project.

**Pull request merged**
