### PR TITLE
Support CRD v1

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Enhancement / new feature

### Description

Support CRD v1

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance ocp4

**Comment by k-wall** [comment]
@kornys upgrade test integration is not done yet, but I'd still appreciate a review at this stage for you opinion on how well this will integrate into CI.

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance ocp4

**Comment by kornys** [comment]
we will probably need to make a many chnges in enmasse-ci also because we pass templates path in pipelines for downstream build

**Comment by k-wall** [comment]
I'm hoping that will be GitHub PR/master working and Jenkin profiles working.  I'll check upgrade test once those are both working on CI.  Things are working locally for my on CRC/OC3.11 with the systests EnMasse operator running the install. @kornys

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance crc

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=upgrade ocp4 testcase=UpgradeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=upgrade ocp4 testcase=UpgradeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=upgrade ocp4 testcase=UpgradeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=upgrade ocp4 testcase=UpgradeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=upgrade ocp4 testcase=UpgradeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=upgrade ocp4 testcase=UpgradeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=upgrade ocp4 testcase=UpgradeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=upgrade ocp4 testcase=UpgradeTest

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance

**Comment by k-wall** [comment]
@kornys @zschwarz @vbusch  I'd like to merge this work soon.  Any comments appreciated.

**Review by kornys — APPROVED** [review]

**Pull request merged**
