### PR TITLE
Remove redundant call to oapi endpoint

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Refactoring

### Description

Remove redundant call to the `oapi` endpoint.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance

**Review by vbusch — APPROVED** [review]
LGTM

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance

**Review by vbusch — APPROVED** [review]

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=acceptance crc

**Pull request merged**
