### PR TITLE
Allow using multiple standard authentication services

### PR DESCRIPTION
**Pull request by lulf**
Look up authentication service based on the authentication service defined in the address space. Code that assumed a single authentication service is rewritten to lookup the authentication service and use that to create the Keycloak client, which is put in a map per authentication service.

(Includes one commit from #2557 to avoid conflicts, will rebase once that is merged).

### CODE REVIEW

**Comment by kornys** [comment]
@lulf going to try my tests against this branch

**Comment by kornys** [comment]
@lulf service broker deployment failed:
```
+++ echo '-DLOG_LEVEL=info -Dvertx.disableDnsResolver=true -Duser.timezone=UTC -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m'
+++ grep -Eq -- '-XX:+ExitOnOutOfMemoryError(=[^ ]*)?(\s|$)'
++ options='-DLOG_LEVEL=info -Dvertx.disableDnsResolver=true -Duser.timezone=UTC -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError'
++ [[ x0 == \x\1 ]]
+++ echo '-DLOG_LEVEL=info -Dvertx.disableDnsResolver=true -Duser.timezone=UTC -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError'
+++ sed -re 's@(--XX:MaxPermSize=[^ ]*)(\s)?@@g'
++ options='-DLOG_LEVEL=info -Dvertx.disableDnsResolver=true -Duser.timezone=UTC -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError'
++ echo '-DLOG_LEVEL=info -Dvertx.disableDnsResolver=true -Duser.timezone=UTC -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError'
+ JAVA_OPTS='-DLOG_LEVEL=info -Dvertx.disableDnsResolver=true -Duser.timezone=UTC -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError '
+ exec java -DLOG_LEVEL=info -Dvertx.disableDnsResolver=true -Duser.timezone=UTC -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -Xms64m -Xmx256m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -jar /service-broker.jar
2019-03-31T15:43:18.849Z INFO  [Version] HV000001: Hibernate Validator null
Mar 31, 2019 3:43:20 PM io.vertx.core.impl.DeploymentManager
SEVERE: No adapter available for type:interface io.fabric8.kubernetes.client.NamespacedKubernetesClient
java.lang.IllegalStateException: No adapter available for type:interface io.fabric8.kubernetes.client.NamespacedKubernetesClient
	at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:134)
	at io.enmasse.osb.ServiceBroker.start(ServiceBroker.java:63)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:494)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by lulf** [comment]
@kornys its related to the othe PR, will fix

**Comment by kornys** [comment]
@lulf also new created standard-authservice contains these errors

[korny-test-f48bd96fc-2kmlq.log](https://github.com/EnMasseProject/enmasse/files/3026830/korny-test-f48bd96fc-2kmlq.log)

**Comment by kornys** [comment]
@lulf is it update of standard authentication service storage supported?

**Comment by lulf** [comment]
@kornys which settings specifically?

**Comment by kornys** [comment]
@lulf change from persistent to ephemeral, or change storage size.

**Comment by lulf** [comment]
@kornys No, that is not supported.

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by kornys** [comment]
@lulf ok, so is it ok that it does not return error on unsupported uppdate?

**Comment by lulf** [comment]
It is the same issue as we have with address plans or other CRDs. We cannot validate changes without an admission controller. We should probably prevent the changes to be applied though and log a warning for instance

**Comment by kornys** [comment]
@lulf ah ok that makes sense. Thanks!

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by lulf** [comment]
@enmasse-ci run tests profile=systemtests-smoke testcase=SmokeTest

**Pull request merged**
