### PR TITLE
Go 1.12 update

### PR DESCRIPTION
**Pull request by secondsun**
A breakup of https://github.com/EnMasseProject/enmasse/pull/2948/ that only includes the fix for https://github.com/EnMasseProject/enmasse/issues/2486

# How to Test 
Ensure you have go 1.12+ installed and run `make`.  Without this PR the vet tool will fail to run, with the vet tool it will run.

### CODE REVIEW

**Comment by k-wall** [comment]
I think this change would mean the minimum Go version would change to 1.12.   See any problems with updating Go now, or any CI implications,  @ctron and @kornys?

This ought to be reflected in the HACKING.md file in the project's root.

**Comment by ctron** [comment]
I think it is ok to move along to Go 1.12. However we should make that a conscious decision, as this also impacts the downstream release. As we do need Go 1.12 support there as well

But I think it makes sens doing the upgrade. And I think we could target that for 0.29. 

@kornys That would mean that we need Go 1.12 images for building.

**Comment by kornys** [comment]
@ctron thb I don't know which version of ho is currently installed on CI images

**Comment by secondsun** [comment]
@k-wall I just tried the command on go 1.10 and it works just fine.  This PR only makes the project buildable in go 1.12

**Comment by ctron** [comment]
I think we should plan to migrate in the next version.

**Pull request merged**
