### PR TITLE
Add test for upgrading IoT components

### PR DESCRIPTION
**Pull request by zschwarz**
### Type of change
- Enhancement / new feature

### Description
Add test for upgrading IoT components
### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke testcase=brokered.SmokeTest#testAddressTypes test_only

**Comment by lulf** [comment]
@kornys Can this be merged?

**Comment by kornys** [comment]
@lulf I'm not sure, because iot upgrade fails as we reported in past

**Comment by lulf** [comment]
@kornys I think we should then:

* Merge this PR and disable test
* Raise issue (or is it already raised?) that iot upgrade fails.

And we can then prioritize the work to fix that.

**Comment by kornys** [comment]
@lulf issue was raised upstream -> #3885
I will wait until Fabian merge his olm upgrade branch, then I will update and merge this with disabled test

**Pull request closed without merging**
