### PR TITLE
Add new default address space plans and address plans

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by rgodfrey** [comment]
@lulf @grs @k-wall So I don't think this is a blocker, but I do find the ordering of the parts of the name slightly odd:

> large-standard-anycast

to me parses as a large "standard anycast" instance. 

As such I think I prefer "standard-large-anycast" or, perhaps even clearer, "standard-anycast-large"

**Comment by lulf** [comment]
@rgodfrey I'm fine with changing that, the current approach is easier to misread I agree.

**Comment by lulf** [comment]
@rgodfrey In that case, should we also change the address space plan names from 'small-standard', 'medium-standard' to 'standard-small', 'standard-medium' etc.?

**Comment by rgodfrey** [comment]
@lulf personally I'd be good with the address space plans being "standard-small", "standard-medium"...  in general _\<what it is\>-\<size\>_

**Pull request merged**
