### PR TITLE
format error message in address list

### PR DESCRIPTION
**Pull request by drcoolsanjeev**
### Type of change
- Bugfix

### Description
- Fix - console address list status message presented as very long single line
- Format the Error message in address list

### CODE REVIEW

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest

**Comment by drcoolsanjeev** [comment]
@enmasse-ci run tests profile=shared testcase=web.**

**Comment by k-wall** [comment]
@drcoolsanjeev  LGTM - much easier to read.

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=*ConsoleTest

**Pull request merged**
