### PR TITLE
Update vertx version to 3.8.3

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by lulf** [comment]
@enmasse-ci run tests profile=iot

**Comment by lulf** [comment]
@enmasse-ci run tests profile=iot testcase=MqttAdapterTest

**Comment by kornys** [comment]
@lulf you should rebase this branch on current master where I pushed a fix for iot api clients

**Comment by lulf** [comment]
@enmasse-ci run tests profile=iot testcase=MqttAdapterTest

**Pull request merged**
