### PR TITLE
Add delegate cache to handle caching of global objects

### PR DESCRIPTION
**Pull request by lulf**
This allows for using both namespaced and global watches based on object
type.

### Type of change

- Enhancement / new feature

### Description

An implementation of controller-runtime Cache interface that delegates lookups and watches to either a local namespaced cache, or a global cache, depending on the type. The type mapping is registered at manager creation time.

The intention is to use this to allow the enmasse-operator deployment to watch both local and global objects.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by kornys** [comment]
@enmasse-ci run tests profile=shared ocp4

**Comment by kornys** [comment]
@lulf I see weir behaviour, it is not related to this PR (but it is a reason why on ocp4 second test failed), when I create address for example standard.address-pepa, delete it and then create again immediately, CR is marked with status Active but broker pod is in state terminating.

**Comment by lulf** [comment]
@kornys I am not totally surprised that this causes issues, because we don't have finalizers for addresses yet, so address is gone even though brokers have still not shut down. So I think the fix for this is to add address finalizer support, which I think we should do soon. In the mean time I would just use a different address.

**Comment by kornys** [comment]
@lulf yup that makes sense, and create one test (disabled) just for finalizers of addresses. I will take care about it.

**Comment by lulf** [comment]
Example usage: https://github.com/lulf/enmasse/blob/convert-messaging-user-crd/cmd/controller-manager/main.go#L49

**Pull request merged**
