### PR TITLE
Add support for specifying router policy

### PR DESCRIPTION
**Pull request by lulf**
* Allows configuring router policy

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=smoke

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=standard.infra.InfraTest

**Comment by k-wall** [comment]
Does this feature have a way to differentiate between user connections (i.e. connections from a user's applications) and connections made internally within EnMasse (e.g. connections from Brokers, MQTT components).   My expectation is that these limits should be applied to the former.

**Comment by grs** [comment]
As specified this policy is applied to all connections. There appears to be no way to associate different policy with different listeners. To apply different policy to internal connections there would need to be a different vhost that they all used or a distinct user group defined.

**Comment by k-wall** [comment]
From the perspective of a user of EnMasse, I would expect the policy controls exposed by EnMasse to be applied to my application traffic.   As a user I should not need to factor in the internal overheads of EnMasse itself.

**Comment by lulf** [comment]
@grs So for internal connections we have 2 options I guess:

1. Change all components to specify an 'internal' vhost. However I guess we cannot enforce external applications to not use this vhost
2. Create a user group defined for internal components. How is the client identified when using TLS client certs? 

I think I would prefer option 2 if we can get that to work.

**Comment by grs** [comment]
If using SASL EXTERNAL, the certificate's subject is used as the identity for the connection.

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=standard.infra.InfraTest

**Comment by lulf** [comment]
@k-wall I think we should go with this scheme for now, and improve it once the router supports per-listener policies.

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=standard.infra.InfraTest

**Pull request merged**
