### PR TITLE
fix loading page rendering for sort

### PR DESCRIPTION
**Pull request by drcoolsanjeev**
### Type of change
- Bugfix

### Description
- Fix issue #1729, 

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests profile=shared testcase=web.**

**Comment by kornys** [comment]
Please rebase this brach on actual master, then I will trigger tests again and see if branch does not brake tests.

**Comment by drcoolsanjeev** [comment]
Branch is rebased on actual master. Please trigger the test again.

**Comment by kornys** [comment]
@enmasse-ci run tests profile=shared testcase=web.**

**Comment by drcoolsanjeev** [comment]
@David, Could you please take a look into this? After the rebase with master, some test are still failing.

**Pull request merged**
