### PR TITLE
switch production console/ui build to use yarn

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Enhancement / new feature

### Description

Switch console UI build from NPM to Yarn.  This is done to synchronise the build with the tool chain used by the developers.  This is done to minimise the chance of regressions in the production build.

The switch from NPM to Yarn was made automatically using `yarn import`.

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
@enmasse-ci run tests profile=shared testcase=brokered.web.FirefoxConsoleTest

**Comment by lulf** [comment]
@k-wall I think we should switch to use yarn for agent as well.

**Comment by rkpattnaik780** [comment]
@k-wall the review with the filters still persist in my system.

**Comment by lulf** [comment]
@enmasse-ci run tests profile=smoke

**Comment by lulf** [comment]
@enmasse-ci run tests profile=smoke

**Pull request merged**
