### PR TITLE
Parse arguments from run phrase

### PR DESCRIPTION
**Pull request by kornys**

### CODE REVIEW

**Comment by kornys** [comment]
run tests @brokered.clients.rhea.**

**Comment by kornys** [comment]
run tests

**Comment by kornys** [comment]
run tests

**Comment by kornys** [comment]
run tests @brokered.clients.rhea

**Comment by kornys** [comment]
run tests @brokered.clients.rhea.**

**Comment by kornys** [comment]
@lulf it's working :-) could you please review it?

**Comment by lulf** [comment]
How about “testcase=...”

**Comment by kornys** [comment]
run tests testcase=brokered.clients.rhea.**

**Comment by kornys** [comment]
@lulf Changed to testcase=

**Comment by kornys** [comment]
run tests testcase=brokered.clients.rhea.**

**Pull request merged**
