### PR TITLE
Use maven batch mode

### PR DESCRIPTION
**Pull request by ctron**
### Type of change

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@enmasse-ci run tests profile=smoke

**Comment by kornys** [comment]
@ctron @lulf see jenkins PR, as I said you `-B` does not hide download status of maven packages...

**Comment by ctron** [comment]
@kornys taking a look at github actions log and jenkins look … you now see the actual downloads, rather than a spamming progress meter. I think it is an improvement.

**Comment by kornys** [comment]
@ctron better is `--no-transfer-progress` if you want to hide download status, but it is available only in maven since 3.6.1

**Comment by ctron** [comment]
> @ctron better is `--no-transfer-progress` if you want to hide download status, but it is available only in maven since 3.6.1

I agree. So let's do that in 3 - 4 years then :grin:

**Pull request merged**
