### PR TITLE
Remove group wildcards special to brokered address space

### PR DESCRIPTION
**Pull request by lulf**
The broker sasl plugin has been updated to handle the same wildcard
syntax as the dispatch router.

### CODE REVIEW

**Comment by ctron** [comment]
Can you use a LinkedHashSet instead of the HashSet, that should keep the order, at least in that piece of code.

**Comment by lulf** [comment]
rerun tests

**Comment by lulf** [comment]
rerun tests

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=brokered.**

**Comment by lulf** [comment]
@rgodfrey Could you check that last commit I made? It seems that Artemis expects that manage_# must exist. I figure its better to put that logic into the plugin so that the auth service API doesn't have to deal with it.

**Comment by lulf** [comment]
@enmasse-ci run tests

**Comment by rgodfrey** [comment]
@lulf I don't really understand your last commit, is it not adding _# to every group?  We wouldn't want that for the non manage_ groups do we?

**Comment by lulf** [comment]
@rgodfrey Just above it does a retainAll on (SPECIAL_AUTHZ_GROUPS) which include 'admin' and 'manage' (so actual will only be manage). What would be the appropriate place to put this you think? I don't understand the code :)

**Comment by rgodfrey** [comment]
@lulf yeah - having spent another 45 seconds reading the code, I think it is fine :)

**Pull request merged**
