### PR TITLE
Add operator metrics

### PR DESCRIPTION
**Pull request by davidffrench**
### Type of change
- Enhancement / new feature

### Description
Relevant issue - https://github.com/EnMasseProject/enmasse/issues/3686
Adding operator metrics to the enmasse operator that are provided by default with the newer versions of the operator SDK. A service and serviceMonitor are created for some prometheus instance to scrape the metrics.

### Verification Steps
1. Install the operator
2. Replace operator image with `quay.io/davidffrench/controller-manager:add-operator-metrics`
3. verify a service and service monitor are created. Both with the label `monitoring-key=middleware`
4. Create two routes based on the service from each port
5. Verify metrics are returning from the route/metrics endpoint
6. Create an address space and address
7. Verify you get reconciliation metrics for the CRDs like so:
```
controller_runtime_reconcile_total{controller="address-space-controller-controller",result="requeue_after"} 50
controller_runtime_reconcile_total{controller="authenticationservice-controller",result="success"} 1
controller_runtime_reconcile_total{controller="consoleservice-controller",result="requeue_after"} 29
```
and
```
# TYPE controller_runtime_reconcile_time_seconds histogram
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="0.005"} 46
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="0.01"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="0.025"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="0.05"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="0.1"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="0.25"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="0.5"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="1"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="2.5"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="5"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="10"} 50
controller_runtime_reconcile_time_seconds_bucket{controller="address-space-controller-controller",le="+Inf"} 50
controller_runtime_reconcile_time_seconds_sum{controller="address-space-controller-controller"} 0.05244756100000001
controller_runtime_reconcile_time_seconds_count{controller="address-space-controller-controller"} 50
```

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

cc @david-martin

### CODE REVIEW

**Comment by davidffrench** [comment]
> @davidffrench Do you have an example of how to adjust the log verbosity now that it no longer is controlled using the env var?

Great question @lulf . This can be done using arguments. This doc outlines how - https://github.com/operator-framework/operator-sdk/blob/master/doc/user/logging.md

The important part on a cluster is this here - https://github.com/operator-framework/operator-sdk/blob/master/doc/user/logging.md#setting-flags-when-deploying-to-a-cluster. You'll notice the args in the operator deployment

**Comment by lulf** [comment]
@davidffrench I'm thinking maybe creation of the ServiceMonitor should be separate. There is ongoing work in creating it based on templates/service-monitors, maybe its best to create it as part of that.

**Comment by davidffrench** [comment]
@lulf That is a possibility. The creation of the service monitor here is the standard format with the operator-sdk and is done through their code, I would recommend against duplicating this into your own repo as it would mean having to manually monitor and update it when the operator-sdk makes updates. Right now it is the responsibility of the operator-sdk to maintain this resource and would be better kept this way in my opinion.

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated

**Comment by davidffrench** [comment]
@lulf What are the next steps to have this merged? Do I need to update the changelog?

I have also rebased off your recent changes

**Comment by lulf** [comment]
@davidffrench The internal CI is running some tests (see https://github.com/EnMasseProject/enmasse/pull/3716#issuecomment-576701483) and I'm just waiting for it to complete before merging.

**Comment by lulf** [comment]
@enmasse-ci run tests profile=iot

**Comment by davidffrench** [comment]
Thanks for the quick response as always @lulf . Changelog has now been updated

**Pull request merged**
