### PR TITLE
Refactored resource handling in system tests

### PR DESCRIPTION
**Pull request by obabec**
- Shared environment resources are now with fully custom infra config
- Also, the shared environment are now created just once for all test with shared address space
- Rearranged code with checkstyle...

### CODE REVIEW

**Comment by obabec** [comment]
@enmasse-ci run tests test_only

**Comment by kornys** [comment]
@enmasse-ci run tests

**Comment by obabec** [comment]
@enmasse-ci run tests

**Comment by obabec** [comment]
@enmasse-ci run tests

**Comment by obabec** [comment]
@enmasse-ci run tests

**Comment by obabec** [comment]
@enmasse-ci run tests test_only

**Comment by obabec** [comment]
@enmasse-ci run tests test_only

**Comment by obabec** [comment]
@enmasse-ci run tests test_only

**Comment by obabec** [comment]
@enmasse-ci run tests test_only

**Comment by obabec** [comment]
@enmasse-ci run tests test_only

**Comment by obabec** [comment]
@enmasse-ci run tests test_only

**Pull request closed without merging**
