### PR TITLE
Console-UI Filter on type and status in address space list is not working when combined together

### PR DESCRIPTION
**Pull request by ajaypratap003**
### Type of change

- Bugfix

### Description
Fixed following issues
1.Fixed filter on name and status together in address space list 
2. Fixed filter on name, namespace, type and status apply all together 

image

image

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ajaypratap003** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest

**Comment by kornys** [comment]
@ajaypratap003 should be this PR in 0.32 release?

**Comment by ajaypratap003** [comment]
> @ajaypratap003 should be this PR in 0.32 release?

@kornys yes, this will be in 0.32 release

**Comment by kornys** [comment]
so it is little bit late I guess, but we will see, anyway you should set milestone

**Comment by ajaypratap003** [comment]
>  **Build Failed**

@kornys @obabec build is failing. I can't ' see build number here. could you please check and let me know if need any change from UI side.

**Comment by lulf** [comment]
@enmasse-ci run tests testcase=FirefoxConsoleTest

**Comment by obabec** [comment]
Manually validated and everything looks OK, systemtests are on the way.

**Comment by lulf** [comment]
@kornys OK to merge?

**Comment by obabec** [comment]
@lulf please wait till tomorrow if it's possible. I am just finishing test and I want to make sure everything is OK.

**Comment by obabec** [comment]
@lulf test is updated. Everything is passing I am cool with merging this now :+1:

**Pull request merged**
