### PR TITLE
Make optional console to check if it affects tests

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by famartinrh** [comment]
@lulf can you rebase this PR with master and run tests again?

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

**Comment by famartinrh** [comment]
systemtests needs a few adjustments to try this, I'm working on that

**Comment by famartinrh** [comment]
testing it here #3932

**Pull request closed without merging**
