### PR TITLE
Address Space Quota Support

### PR DESCRIPTION
**Pull request by lulf**

### CODE REVIEW

**Comment by lulf** [comment]
@rgodfrey I'm tempted to say we should not touch the users instances if the quota is changed but state that it only affects creating new address spaces.

I'm imagining a scenario where a quota change was applied by mistake, causing deletion of address spaces. And it would have to choose a random (or using some heuristic) candidate to delete. 

We could also consider a hard vs. soft limit, where lowering the hard limit could case address spaces to be deleted, whereas the soft limit would allow the count to go above for existing address spaces. 

I'm not sure if it matters in practice, i.e. one could periodically check users going above the quota, and then 'manually' interact with users to resolve the issue.

**Comment by rgodfrey** [comment]
@lulf so I think it would be useful if there were an easy way to extract a "users over quota" list, possibly including all the addressspaces associated with the user... where do you think the best place to implement that would be?

**Comment by lulf** [comment]
@rgodfrey How about a REST endpoint like:

POST /apis/enmasse.io/v1alpha1/addressspacequotareviews

Payload
```
apiVersion: enmasse.io/v1alpha1
kind: AddressSpaceQuotaReview
spec:
  user: developer
```

Response
```
apiVersion: enmasse.io/v1alpha1
kind: AddressSpaceQuotaReview
spec:
  user: developer
status:
  exceeded: false
```

Modelled after token reviews and subject access reviews in kubernetes:

https://kubernetes.io/docs/reference/access-authn-authz/authorization/

**Comment by rgodfrey** [comment]
@lulf works for me

**Comment by lulf** [comment]
@rgodfrey Need real-time edits :) I  had not considered the quota delete case for the second alternative, good point.

I think the first alternative is fine then.

**Comment by lulf** [comment]
@rgodfrey Updated the design doc with the changes

**Comment by lulf** [comment]
Closing PR due to inactivity. Consider implementing this using admission hooks instead.

**Pull request closed without merging**
