### PR TITLE
Test verifying Agent's behaviour when connection to the Kubernetes API server is lost

### PR DESCRIPTION
**Pull request by k-wall**
### Type of change

- Enhancement / new feature

### Description

System test verifying behaviour when connection to the Kubernetes API server is lost

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [ ] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by k-wall** [comment]
Originally I thought we could apply the same technique to the standard-controller and the address-space-controler but as these components, properly validate trust, this fails.

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=CommonTest  test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=CommonTest test_only

**Comment by k-wall** [comment]
> Would an alternative to use a separate proxy process be to create an openshift route to the api server and delete it to simulate failure?

Interesting idea. Less stuff is always appealing. You mean create a openshift route to kubernetes.default.svc?   Is it possible for a route to reference a service in another namespace?

**Comment by lulf** [comment]
> Interesting idea. Less stuff is always appealing. You mean create a openshift route to kubernetes.default.svc? Is it possible for a route to reference a service in another namespace?

Yes, but you'd have to create the route in the 'default' namespace, which I think the tests have permission to do anyway.

**Comment by k-wall** [comment]
I tested your approach manually (a route in the default namespace to `kubernetes.default.svc` with TLS `passthrough`), it works but a drawback and some different behaviour which I like to discuss.

* Deleting the route does not break the *established* connections.  (I think this is expected behaviour.  The OpenShift route must implement a socket listener somewhere. Once the socket connection is established, I think its role is at an end).  The upshot for this test is the Agent's existing watch doesn't fail.  However when it times out (we could tune RESYNC_INTERVAL for the nest), the next attempted connection does.   The proxy approach doesn't suffer from this, as the proxy dies, the established connection goes with it.

* When the route is absent, the Agent sees OpenShift's HTML Application in not available (503 service temp unavailable).  The Agent handles this error fine and the error path is the same from the Agent's point of view.    With the proxy approach, the Agent sees a resolution error when poxy deployment is scaled down.

btw Neither approach work of the box for standard-controller.  Proxy approach fails the TLS owing to trust (unexpected cert), Route approach passes TLS trust but fails the hostname validation. If we wanted to test standard-controller (and address-space-controller and the operator), we'd need a switch to disable trust for the system test, which displeases.

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=CommonTest test_only

**Comment by k-wall** [comment]
@enmasse-ci run tests testcase=CommonTest test_only

**Comment by lulf** [comment]
> I tested your approach manually (a route in the default namespace to `kubernetes.default.svc` with TLS `passthrough`), it works but there is a drawback and some different behaviour which I like to discuss.
> 
>     * Deleting the route does not break the _established_ connections.  (I think this is expected behaviour.  The OpenShift route must implement a socket listener somewhere. Once the socket connection is established, I think its role is at an end).  The upshot for this test is the Agent's existing watch doesn't fail.  However when it times out (we could tune RESYNC_INTERVAL for the test), the next attempted connection does.   The proxy approach doesn't suffer from this, as the proxy dies, the established connection goes with it.
> 
>     * When the route is absent, the Agent sees OpenShift's HTML Application in not available (503 service temp unavailable).  The Agent handles this error fine and the error path is the same from the Agent's point of view.    With the proxy approach, the Agent sees a resolution error when proxy deployment is scaled down.
> 
> 
> btw Neither approach work of the box for standard-controller. Proxy approach fails the TLS owing to trust (unexpected cert), Route approach passes TLS trust but fails the hostname validation. If we wanted to test standard-controller (and address-space-controller and the operator), we'd need a switch to disable trust for the system test, which displeases.
> 
> WDYT?

I'm fine with either approach but maybe the api-proxy approach is the most realistic, so I'd say go for that. For the standard-controller we could pass controller parameters to instruct it to trust everything for instance. However, since I think we haven't seen the standard-controller having this issue I'm relaxed about adding that to the mix.

**Comment by k-wall** [comment]
> > I tested your approach manually (a route in the default namespace to `kubernetes.default.svc` with TLS `passthrough`), it works but there is a drawback and some different behaviour which I like to discuss.
> > ```
> > * Deleting the route does not break the _established_ connections.  (I think this is expected behaviour.  The OpenShift route must implement a socket listener somewhere. Once the socket connection is established, I think its role is at an end).  The upshot for this test is the Agent's existing watch doesn't fail.  However when it times out (we could tune RESYNC_INTERVAL for the test), the next attempted connection does.   The proxy approach doesn't suffer from this, as the proxy dies, the established connection goes with it.
> > 
> > * When the route is absent, the Agent sees OpenShift's HTML Application in not available (503 service temp unavailable).  The Agent handles this error fine and the error path is the same from the Agent's point of view.    With the proxy approach, the Agent sees a resolution error when proxy deployment is scaled down.
> > ```
> > 
> > 
> > btw Neither approach work of the box for standard-controller. Proxy approach fails the TLS owing to trust (unexpected cert), Route approach passes TLS trust but fails the hostname validation. If we wanted to test standard-controller (and address-space-controller and the operator), we'd need a switch to disable trust for the system test, which displeases.
> > WDYT?
> 
> I'm fine with either approach but maybe the api-proxy approach is the most realistic, so I'd say go for that. For the standard-controller we could pass controller parameters to instruct it to trust everything for instance. However, since I think we haven't seen the standard-controller having this issue I'm relaxed about adding that to the mix.

Thanks - I'll keep the api-proxy approach.  I'm not advocating adding coverage for standard controller and other components at the moment.

**Comment by k-wall** [comment]
@kornys would you mind reviewing?

**Comment by kornys** [comment]
@k-wall LGTM in general, good job, just question about test -> do you want to backport this test into 0.30.x or you will merge this test into current master as well?

**Comment by k-wall** [comment]
> @k-wall LGTM in general, good job, just question about test -> do you want to backport this test into 0.30.x or you will merge this test into current master as well?

I think given we have so much non library code in Agent, handling our kubernetes interaction having it in master is valuable as it helps guards against regression.    So I'm thinking master + release-0.30.

**Pull request merged**
